// Code generated by ros2gen. DO NOT EDIT.

package rcl_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rcl_interfaces/srv/describe_parameters.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("rcl_interfaces/DescribeParameters", DescribeParametersTypeSupport)
	<no value>.RegisterService("rcl_interfaces/srv/DescribeParameters", DescribeParametersTypeSupport)
}

type _DescribeParametersTypeSupport struct {}

func (s _DescribeParametersTypeSupport) Request() <no value>.MessageTypeSupport {
	return DescribeParameters_RequestTypeSupport
}

func (s _DescribeParametersTypeSupport) Response() <no value>.MessageTypeSupport {
	return DescribeParameters_ResponseTypeSupport
}

func (s _DescribeParametersTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rcl_interfaces__srv__DescribeParameters())
}

// Modifying this variable is undefined behavior.
var DescribeParametersTypeSupport <no value>.ServiceTypeSupport = _DescribeParametersTypeSupport{}

// DescribeParametersClient wraps <no value>.Client to provide type safe helper
// functions
type DescribeParametersClient struct {
	*<no value>.Client
}

// NewDescribeParametersClient creates and returns a new client for the
// DescribeParameters
func NewDescribeParametersClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*DescribeParametersClient, error) {
	client, err := node.NewClient(serviceName, DescribeParametersTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DescribeParametersClient{client}, nil
}

func (s *DescribeParametersClient) Send(ctx context.Context, req *DescribeParameters_Request) (*DescribeParameters_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*DescribeParameters_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type DescribeParametersServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s DescribeParametersServiceResponseSender) SendResponse(resp *DescribeParameters_Response) error {
	return s.sender.SendResponse(resp)
}

type DescribeParametersServiceRequestHandler func(*<no value>.ServiceInfo, *DescribeParameters_Request, DescribeParametersServiceResponseSender)

// DescribeParametersService wraps <no value>.Service to provide type safe helper
// functions
type DescribeParametersService struct {
	*<no value>.Service
}

// NewDescribeParametersService creates and returns a new service for the
// DescribeParameters
func NewDescribeParametersService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler DescribeParametersServiceRequestHandler) (*DescribeParametersService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*DescribeParameters_Request)
		responseSender := DescribeParametersServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, DescribeParametersTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &DescribeParametersService{service}, nil
}