// Code generated by ros2gen. DO NOT EDIT.

package rcl_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rcl_interfaces/srv/get_parameters.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("rcl_interfaces/GetParameters", GetParametersTypeSupport)
	<no value>.RegisterService("rcl_interfaces/srv/GetParameters", GetParametersTypeSupport)
}

type _GetParametersTypeSupport struct {}

func (s _GetParametersTypeSupport) Request() <no value>.MessageTypeSupport {
	return GetParameters_RequestTypeSupport
}

func (s _GetParametersTypeSupport) Response() <no value>.MessageTypeSupport {
	return GetParameters_ResponseTypeSupport
}

func (s _GetParametersTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rcl_interfaces__srv__GetParameters())
}

// Modifying this variable is undefined behavior.
var GetParametersTypeSupport <no value>.ServiceTypeSupport = _GetParametersTypeSupport{}

// GetParametersClient wraps <no value>.Client to provide type safe helper
// functions
type GetParametersClient struct {
	*<no value>.Client
}

// NewGetParametersClient creates and returns a new client for the
// GetParameters
func NewGetParametersClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*GetParametersClient, error) {
	client, err := node.NewClient(serviceName, GetParametersTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetParametersClient{client}, nil
}

func (s *GetParametersClient) Send(ctx context.Context, req *GetParameters_Request) (*GetParameters_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetParameters_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetParametersServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s GetParametersServiceResponseSender) SendResponse(resp *GetParameters_Response) error {
	return s.sender.SendResponse(resp)
}

type GetParametersServiceRequestHandler func(*<no value>.ServiceInfo, *GetParameters_Request, GetParametersServiceResponseSender)

// GetParametersService wraps <no value>.Service to provide type safe helper
// functions
type GetParametersService struct {
	*<no value>.Service
}

// NewGetParametersService creates and returns a new service for the
// GetParameters
func NewGetParametersService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler GetParametersServiceRequestHandler) (*GetParametersService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*GetParameters_Request)
		responseSender := GetParametersServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetParametersTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetParametersService{service}, nil
}