// Code generated by ros2gen. DO NOT EDIT.

package realsense2_camera_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <realsense2_camera_msgs/srv/calib_config_read.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("realsense2_camera_msgs/CalibConfigRead", CalibConfigReadTypeSupport)
	<no value>.RegisterService("realsense2_camera_msgs/srv/CalibConfigRead", CalibConfigReadTypeSupport)
}

type _CalibConfigReadTypeSupport struct {}

func (s _CalibConfigReadTypeSupport) Request() <no value>.MessageTypeSupport {
	return CalibConfigRead_RequestTypeSupport
}

func (s _CalibConfigReadTypeSupport) Response() <no value>.MessageTypeSupport {
	return CalibConfigRead_ResponseTypeSupport
}

func (s _CalibConfigReadTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__realsense2_camera_msgs__srv__CalibConfigRead())
}

// Modifying this variable is undefined behavior.
var CalibConfigReadTypeSupport <no value>.ServiceTypeSupport = _CalibConfigReadTypeSupport{}

// CalibConfigReadClient wraps <no value>.Client to provide type safe helper
// functions
type CalibConfigReadClient struct {
	*<no value>.Client
}

// NewCalibConfigReadClient creates and returns a new client for the
// CalibConfigRead
func NewCalibConfigReadClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*CalibConfigReadClient, error) {
	client, err := node.NewClient(serviceName, CalibConfigReadTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &CalibConfigReadClient{client}, nil
}

func (s *CalibConfigReadClient) Send(ctx context.Context, req *CalibConfigRead_Request) (*CalibConfigRead_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*CalibConfigRead_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type CalibConfigReadServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s CalibConfigReadServiceResponseSender) SendResponse(resp *CalibConfigRead_Response) error {
	return s.sender.SendResponse(resp)
}

type CalibConfigReadServiceRequestHandler func(*<no value>.ServiceInfo, *CalibConfigRead_Request, CalibConfigReadServiceResponseSender)

// CalibConfigReadService wraps <no value>.Service to provide type safe helper
// functions
type CalibConfigReadService struct {
	*<no value>.Service
}

// NewCalibConfigReadService creates and returns a new service for the
// CalibConfigRead
func NewCalibConfigReadService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler CalibConfigReadServiceRequestHandler) (*CalibConfigReadService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*CalibConfigRead_Request)
		responseSender := CalibConfigReadServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, CalibConfigReadTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &CalibConfigReadService{service}, nil
}