// Code generated by ros2gen. DO NOT EDIT.

package lifecycle_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <lifecycle_msgs/srv/get_available_states.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("lifecycle_msgs/GetAvailableStates", GetAvailableStatesTypeSupport)
	<no value>.RegisterService("lifecycle_msgs/srv/GetAvailableStates", GetAvailableStatesTypeSupport)
}

type _GetAvailableStatesTypeSupport struct {}

func (s _GetAvailableStatesTypeSupport) Request() <no value>.MessageTypeSupport {
	return GetAvailableStates_RequestTypeSupport
}

func (s _GetAvailableStatesTypeSupport) Response() <no value>.MessageTypeSupport {
	return GetAvailableStates_ResponseTypeSupport
}

func (s _GetAvailableStatesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__lifecycle_msgs__srv__GetAvailableStates())
}

// Modifying this variable is undefined behavior.
var GetAvailableStatesTypeSupport <no value>.ServiceTypeSupport = _GetAvailableStatesTypeSupport{}

// GetAvailableStatesClient wraps <no value>.Client to provide type safe helper
// functions
type GetAvailableStatesClient struct {
	*<no value>.Client
}

// NewGetAvailableStatesClient creates and returns a new client for the
// GetAvailableStates
func NewGetAvailableStatesClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*GetAvailableStatesClient, error) {
	client, err := node.NewClient(serviceName, GetAvailableStatesTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetAvailableStatesClient{client}, nil
}

func (s *GetAvailableStatesClient) Send(ctx context.Context, req *GetAvailableStates_Request) (*GetAvailableStates_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetAvailableStates_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetAvailableStatesServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s GetAvailableStatesServiceResponseSender) SendResponse(resp *GetAvailableStates_Response) error {
	return s.sender.SendResponse(resp)
}

type GetAvailableStatesServiceRequestHandler func(*<no value>.ServiceInfo, *GetAvailableStates_Request, GetAvailableStatesServiceResponseSender)

// GetAvailableStatesService wraps <no value>.Service to provide type safe helper
// functions
type GetAvailableStatesService struct {
	*<no value>.Service
}

// NewGetAvailableStatesService creates and returns a new service for the
// GetAvailableStates
func NewGetAvailableStatesService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler GetAvailableStatesServiceRequestHandler) (*GetAvailableStatesService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*GetAvailableStates_Request)
		responseSender := GetAvailableStatesServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetAvailableStatesTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetAvailableStatesService{service}, nil
}