// Code generated by ros2gen. DO NOT EDIT.

package lifecycle_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <lifecycle_msgs/srv/get_state.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("lifecycle_msgs/GetState", GetStateTypeSupport)
	<no value>.RegisterService("lifecycle_msgs/srv/GetState", GetStateTypeSupport)
}

type _GetStateTypeSupport struct {}

func (s _GetStateTypeSupport) Request() <no value>.MessageTypeSupport {
	return GetState_RequestTypeSupport
}

func (s _GetStateTypeSupport) Response() <no value>.MessageTypeSupport {
	return GetState_ResponseTypeSupport
}

func (s _GetStateTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__lifecycle_msgs__srv__GetState())
}

// Modifying this variable is undefined behavior.
var GetStateTypeSupport <no value>.ServiceTypeSupport = _GetStateTypeSupport{}

// GetStateClient wraps <no value>.Client to provide type safe helper
// functions
type GetStateClient struct {
	*<no value>.Client
}

// NewGetStateClient creates and returns a new client for the
// GetState
func NewGetStateClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*GetStateClient, error) {
	client, err := node.NewClient(serviceName, GetStateTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetStateClient{client}, nil
}

func (s *GetStateClient) Send(ctx context.Context, req *GetState_Request) (*GetState_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetState_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetStateServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s GetStateServiceResponseSender) SendResponse(resp *GetState_Response) error {
	return s.sender.SendResponse(resp)
}

type GetStateServiceRequestHandler func(*<no value>.ServiceInfo, *GetState_Request, GetStateServiceResponseSender)

// GetStateService wraps <no value>.Service to provide type safe helper
// functions
type GetStateService struct {
	*<no value>.Service
}

// NewGetStateService creates and returns a new service for the
// GetState
func NewGetStateService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler GetStateServiceRequestHandler) (*GetStateService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*GetState_Request)
		responseSender := GetStateServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetStateTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetStateService{service}, nil
}