// Code generated by ros2gen. DO NOT EDIT.

package std_srvs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <std_srvs/srv/empty.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("std_srvs/Empty", EmptyTypeSupport)
	<no value>.RegisterService("std_srvs/srv/Empty", EmptyTypeSupport)
}

type _EmptyTypeSupport struct {}

func (s _EmptyTypeSupport) Request() <no value>.MessageTypeSupport {
	return Empty_RequestTypeSupport
}

func (s _EmptyTypeSupport) Response() <no value>.MessageTypeSupport {
	return Empty_ResponseTypeSupport
}

func (s _EmptyTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__std_srvs__srv__Empty())
}

// Modifying this variable is undefined behavior.
var EmptyTypeSupport <no value>.ServiceTypeSupport = _EmptyTypeSupport{}

// EmptyClient wraps <no value>.Client to provide type safe helper
// functions
type EmptyClient struct {
	*<no value>.Client
}

// NewEmptyClient creates and returns a new client for the
// Empty
func NewEmptyClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*EmptyClient, error) {
	client, err := node.NewClient(serviceName, EmptyTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &EmptyClient{client}, nil
}

func (s *EmptyClient) Send(ctx context.Context, req *Empty_Request) (*Empty_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Empty_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type EmptyServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s EmptyServiceResponseSender) SendResponse(resp *Empty_Response) error {
	return s.sender.SendResponse(resp)
}

type EmptyServiceRequestHandler func(*<no value>.ServiceInfo, *Empty_Request, EmptyServiceResponseSender)

// EmptyService wraps <no value>.Service to provide type safe helper
// functions
type EmptyService struct {
	*<no value>.Service
}

// NewEmptyService creates and returns a new service for the
// Empty
func NewEmptyService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler EmptyServiceRequestHandler) (*EmptyService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*Empty_Request)
		responseSender := EmptyServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, EmptyTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &EmptyService{service}, nil
}