// Code generated by ros2gen. DO NOT EDIT.

package composition_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <composition_interfaces/srv/list_nodes.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("composition_interfaces/ListNodes", ListNodesTypeSupport)
	<no value>.RegisterService("composition_interfaces/srv/ListNodes", ListNodesTypeSupport)
}

type _ListNodesTypeSupport struct {}

func (s _ListNodesTypeSupport) Request() <no value>.MessageTypeSupport {
	return ListNodes_RequestTypeSupport
}

func (s _ListNodesTypeSupport) Response() <no value>.MessageTypeSupport {
	return ListNodes_ResponseTypeSupport
}

func (s _ListNodesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__composition_interfaces__srv__ListNodes())
}

// Modifying this variable is undefined behavior.
var ListNodesTypeSupport <no value>.ServiceTypeSupport = _ListNodesTypeSupport{}

// ListNodesClient wraps <no value>.Client to provide type safe helper
// functions
type ListNodesClient struct {
	*<no value>.Client
}

// NewListNodesClient creates and returns a new client for the
// ListNodes
func NewListNodesClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*ListNodesClient, error) {
	client, err := node.NewClient(serviceName, ListNodesTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListNodesClient{client}, nil
}

func (s *ListNodesClient) Send(ctx context.Context, req *ListNodes_Request) (*ListNodes_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ListNodes_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ListNodesServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s ListNodesServiceResponseSender) SendResponse(resp *ListNodes_Response) error {
	return s.sender.SendResponse(resp)
}

type ListNodesServiceRequestHandler func(*<no value>.ServiceInfo, *ListNodes_Request, ListNodesServiceResponseSender)

// ListNodesService wraps <no value>.Service to provide type safe helper
// functions
type ListNodesService struct {
	*<no value>.Service
}

// NewListNodesService creates and returns a new service for the
// ListNodes
func NewListNodesService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler ListNodesServiceRequestHandler) (*ListNodesService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*ListNodes_Request)
		responseSender := ListNodesServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ListNodesTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ListNodesService{service}, nil
}