// Code generated by ros2gen. DO NOT EDIT.

package diagnostic_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <diagnostic_msgs/srv/add_diagnostics.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("diagnostic_msgs/AddDiagnostics", AddDiagnosticsTypeSupport)
	<no value>.RegisterService("diagnostic_msgs/srv/AddDiagnostics", AddDiagnosticsTypeSupport)
}

type _AddDiagnosticsTypeSupport struct {}

func (s _AddDiagnosticsTypeSupport) Request() <no value>.MessageTypeSupport {
	return AddDiagnostics_RequestTypeSupport
}

func (s _AddDiagnosticsTypeSupport) Response() <no value>.MessageTypeSupport {
	return AddDiagnostics_ResponseTypeSupport
}

func (s _AddDiagnosticsTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__diagnostic_msgs__srv__AddDiagnostics())
}

// Modifying this variable is undefined behavior.
var AddDiagnosticsTypeSupport <no value>.ServiceTypeSupport = _AddDiagnosticsTypeSupport{}

// AddDiagnosticsClient wraps <no value>.Client to provide type safe helper
// functions
type AddDiagnosticsClient struct {
	*<no value>.Client
}

// NewAddDiagnosticsClient creates and returns a new client for the
// AddDiagnostics
func NewAddDiagnosticsClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*AddDiagnosticsClient, error) {
	client, err := node.NewClient(serviceName, AddDiagnosticsTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &AddDiagnosticsClient{client}, nil
}

func (s *AddDiagnosticsClient) Send(ctx context.Context, req *AddDiagnostics_Request) (*AddDiagnostics_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*AddDiagnostics_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type AddDiagnosticsServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s AddDiagnosticsServiceResponseSender) SendResponse(resp *AddDiagnostics_Response) error {
	return s.sender.SendResponse(resp)
}

type AddDiagnosticsServiceRequestHandler func(*<no value>.ServiceInfo, *AddDiagnostics_Request, AddDiagnosticsServiceResponseSender)

// AddDiagnosticsService wraps <no value>.Service to provide type safe helper
// functions
type AddDiagnosticsService struct {
	*<no value>.Service
}

// NewAddDiagnosticsService creates and returns a new service for the
// AddDiagnostics
func NewAddDiagnosticsService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler AddDiagnosticsServiceRequestHandler) (*AddDiagnosticsService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*AddDiagnostics_Request)
		responseSender := AddDiagnosticsServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, AddDiagnosticsTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &AddDiagnosticsService{service}, nil
}