// Code generated by ros2gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/is_paused.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("rosbag2_interfaces/IsPaused", IsPausedTypeSupport)
	<no value>.RegisterService("rosbag2_interfaces/srv/IsPaused", IsPausedTypeSupport)
}

type _IsPausedTypeSupport struct {}

func (s _IsPausedTypeSupport) Request() <no value>.MessageTypeSupport {
	return IsPaused_RequestTypeSupport
}

func (s _IsPausedTypeSupport) Response() <no value>.MessageTypeSupport {
	return IsPaused_ResponseTypeSupport
}

func (s _IsPausedTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__IsPaused())
}

// Modifying this variable is undefined behavior.
var IsPausedTypeSupport <no value>.ServiceTypeSupport = _IsPausedTypeSupport{}

// IsPausedClient wraps <no value>.Client to provide type safe helper
// functions
type IsPausedClient struct {
	*<no value>.Client
}

// NewIsPausedClient creates and returns a new client for the
// IsPaused
func NewIsPausedClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*IsPausedClient, error) {
	client, err := node.NewClient(serviceName, IsPausedTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IsPausedClient{client}, nil
}

func (s *IsPausedClient) Send(ctx context.Context, req *IsPaused_Request) (*IsPaused_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*IsPaused_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type IsPausedServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s IsPausedServiceResponseSender) SendResponse(resp *IsPaused_Response) error {
	return s.sender.SendResponse(resp)
}

type IsPausedServiceRequestHandler func(*<no value>.ServiceInfo, *IsPaused_Request, IsPausedServiceResponseSender)

// IsPausedService wraps <no value>.Service to provide type safe helper
// functions
type IsPausedService struct {
	*<no value>.Service
}

// NewIsPausedService creates and returns a new service for the
// IsPaused
func NewIsPausedService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler IsPausedServiceRequestHandler) (*IsPausedService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*IsPaused_Request)
		responseSender := IsPausedServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, IsPausedTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &IsPausedService{service}, nil
}