// Code generated by ros2gen. DO NOT EDIT.

package rosbag2_interfaces_srv

import (
	"unsafe"

	"github.com/okieraised/rclgo/pkg/rclgo"
	"github.com/okieraised/rclgo/pkg/rclgo/typemap"
	"github.com/okieraised/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/play.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Play_Response", Play_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/Play_Response", Play_ResponseTypeSupport)
}

type Play_Response struct {
	Success bool `yaml:"success"` // returns false when another playback execution is running, otherwise true
}

// NewPlay_Response creates a new Play_Response with default values.
func NewPlay_Response() *Play_Response {
	self := Play_Response{}
	self.SetDefaults()
	return &self
}

func (t *Play_Response) Clone() *Play_Response {
	c := &Play_Response{}
	c.Success = t.Success
	return c
}

func (t *Play_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Play_Response) SetDefaults() {
	t.Success = false
}

func (t *Play_Response) GetTypeSupport() types.MessageTypeSupport {
	return Play_ResponseTypeSupport
}

// Play_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Play_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewPlay_ResponsePublisher creates and returns a new publisher for the
// Play_Response
func NewPlay_ResponsePublisher(node *rclgo.Node, topicName string, options *rclgo.PublisherOptions) (*Play_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, Play_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Play_ResponsePublisher{pub}, nil
}

func (p *Play_ResponsePublisher) Publish(msg *Play_Response) error {
	return p.Publisher.Publish(msg)
}

// Play_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Play_ResponseSubscription struct {
	*rclgo.Subscription
}

// Play_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Play_ResponseSubscription.
type Play_ResponseSubscriptionCallback func(msg *Play_Response, info *rclgo.MessageInfo, err error)

// NewPlay_ResponseSubscription creates and returns a new subscription for the
// Play_Response
func NewPlay_ResponseSubscription(node *rclgo.Node, topicName string, opts *rclgo.SubscriptionOptions, subscriptionCallback Play_ResponseSubscriptionCallback) (*Play_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Play_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, Play_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Play_ResponseSubscription{sub}, nil
}

func (s *Play_ResponseSubscription) TakeMessage(out *Play_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// ClonePlay_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePlay_ResponseSlice(dst, src []Play_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Play_ResponseTypeSupport types.MessageTypeSupport = _Play_ResponseTypeSupport{}

type _Play_ResponseTypeSupport struct{}

func (t _Play_ResponseTypeSupport) New() types.Message {
	return NewPlay_Response()
}

func (t _Play_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Play_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Play_Response__create())
}

func (t _Play_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Play_Response__destroy((*C.rosbag2_interfaces__srv__Play_Response)(pointer_to_free))
}

func (t _Play_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Play_Response)
	mem := (*C.rosbag2_interfaces__srv__Play_Response)(dst)
	mem.success = C.bool(m.Success)
}

func (t _Play_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Play_Response)
	mem := (*C.rosbag2_interfaces__srv__Play_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
}

func (t _Play_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Play_Response())
}

type CPlay_Response = C.rosbag2_interfaces__srv__Play_Response
type CPlay_ResponseSequence = C.rosbag2_interfaces__srv__Play_Response__Sequence

func Play_ResponseSequenceToGo(goSlice *[]Play_Response, cSlice CPlay_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Play_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Play_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func Play_ResponseSequenceToC(cSlice *CPlay_ResponseSequence, goSlice []Play_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Play_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__Play_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Play_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func Play_ResponseArrayToGo(goSlice []Play_Response, cSlice []CPlay_Response) {
	for i := 0; i < len(cSlice); i++ {
		Play_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func Play_ResponseArrayToC(cSlice []CPlay_Response, goSlice []Play_Response) {
	for i := 0; i < len(goSlice); i++ {
		Play_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
