// Code generated by ros2gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/play.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/pkg/rclgo"
	"github.com/okieraised/rclgo/pkg/rclgo/typemap"
	"github.com/okieraised/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/Play", PlayTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/Play", PlayTypeSupport)
}

type _PlayTypeSupport struct{}

func (s _PlayTypeSupport) Request() types.MessageTypeSupport {
	return Play_RequestTypeSupport
}

func (s _PlayTypeSupport) Response() types.MessageTypeSupport {
	return Play_ResponseTypeSupport
}

func (s _PlayTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__Play())
}

// Modifying this variable is undefined behavior.
var PlayTypeSupport types.ServiceTypeSupport = _PlayTypeSupport{}

// PlayClient wraps rclgo.Client to provide type safe helper
// functions
type PlayClient struct {
	*rclgo.Client
}

// NewPlayClient creates and returns a new client for the
// Play
func NewPlayClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*PlayClient, error) {
	client, err := node.NewClient(serviceName, PlayTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PlayClient{client}, nil
}

func (s *PlayClient) Send(ctx context.Context, req *Play_Request) (*Play_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Play_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type PlayServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s PlayServiceResponseSender) SendResponse(resp *Play_Response) error {
	return s.sender.SendResponse(resp)
}

type PlayServiceRequestHandler func(*rclgo.ServiceInfo, *Play_Request, PlayServiceResponseSender)

// PlayService wraps rclgo.Service to provide type safe helper
// functions
type PlayService struct {
	*rclgo.Service
}

// NewPlayService creates and returns a new service for the
// Play
func NewPlayService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler PlayServiceRequestHandler) (*PlayService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*Play_Request)
		responseSender := PlayServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, PlayTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &PlayService{service}, nil
}
