// Code generated by ros2gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/seek.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("rosbag2_interfaces/Seek", SeekTypeSupport)
	<no value>.RegisterService("rosbag2_interfaces/srv/Seek", SeekTypeSupport)
}

type _SeekTypeSupport struct {}

func (s _SeekTypeSupport) Request() <no value>.MessageTypeSupport {
	return Seek_RequestTypeSupport
}

func (s _SeekTypeSupport) Response() <no value>.MessageTypeSupport {
	return Seek_ResponseTypeSupport
}

func (s _SeekTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__Seek())
}

// Modifying this variable is undefined behavior.
var SeekTypeSupport <no value>.ServiceTypeSupport = _SeekTypeSupport{}

// SeekClient wraps <no value>.Client to provide type safe helper
// functions
type SeekClient struct {
	*<no value>.Client
}

// NewSeekClient creates and returns a new client for the
// Seek
func NewSeekClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*SeekClient, error) {
	client, err := node.NewClient(serviceName, SeekTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SeekClient{client}, nil
}

func (s *SeekClient) Send(ctx context.Context, req *Seek_Request) (*Seek_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Seek_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SeekServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s SeekServiceResponseSender) SendResponse(resp *Seek_Response) error {
	return s.sender.SendResponse(resp)
}

type SeekServiceRequestHandler func(*<no value>.ServiceInfo, *Seek_Request, SeekServiceResponseSender)

// SeekService wraps <no value>.Service to provide type safe helper
// functions
type SeekService struct {
	*<no value>.Service
}

// NewSeekService creates and returns a new service for the
// Seek
func NewSeekService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler SeekServiceRequestHandler) (*SeekService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*Seek_Request)
		responseSender := SeekServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SeekTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SeekService{service}, nil
}