// Code generated by ros2gen. DO NOT EDIT.

package rosbag2_interfaces_srv

import (
	"unsafe"

	"github.com/okieraised/rclgo/pkg/rclgo"
	"github.com/okieraised/rclgo/pkg/rclgo/typemap"
	"github.com/okieraised/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/stop.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Stop_Request", Stop_RequestTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/Stop_Request", Stop_RequestTypeSupport)
}

type Stop_Request struct {
}

// NewStop_Request creates a new Stop_Request with default values.
func NewStop_Request() *Stop_Request {
	self := Stop_Request{}
	self.SetDefaults()
	return &self
}

func (t *Stop_Request) Clone() *Stop_Request {
	c := &Stop_Request{}
	return c
}

func (t *Stop_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Stop_Request) SetDefaults() {
}

func (t *Stop_Request) GetTypeSupport() types.MessageTypeSupport {
	return Stop_RequestTypeSupport
}

// Stop_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Stop_RequestPublisher struct {
	*rclgo.Publisher
}

// NewStop_RequestPublisher creates and returns a new publisher for the
// Stop_Request
func NewStop_RequestPublisher(node *rclgo.Node, topicName string, options *rclgo.PublisherOptions) (*Stop_RequestPublisher, error) {
	pub, err := node.NewPublisher(topicName, Stop_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Stop_RequestPublisher{pub}, nil
}

func (p *Stop_RequestPublisher) Publish(msg *Stop_Request) error {
	return p.Publisher.Publish(msg)
}

// Stop_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Stop_RequestSubscription struct {
	*rclgo.Subscription
}

// Stop_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a Stop_RequestSubscription.
type Stop_RequestSubscriptionCallback func(msg *Stop_Request, info *rclgo.MessageInfo, err error)

// NewStop_RequestSubscription creates and returns a new subscription for the
// Stop_Request
func NewStop_RequestSubscription(node *rclgo.Node, topicName string, opts *rclgo.SubscriptionOptions, subscriptionCallback Stop_RequestSubscriptionCallback) (*Stop_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Stop_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, Stop_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Stop_RequestSubscription{sub}, nil
}

func (s *Stop_RequestSubscription) TakeMessage(out *Stop_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneStop_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneStop_RequestSlice(dst, src []Stop_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Stop_RequestTypeSupport types.MessageTypeSupport = _Stop_RequestTypeSupport{}

type _Stop_RequestTypeSupport struct{}

func (t _Stop_RequestTypeSupport) New() types.Message {
	return NewStop_Request()
}

func (t _Stop_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Stop_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Stop_Request__create())
}

func (t _Stop_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Stop_Request__destroy((*C.rosbag2_interfaces__srv__Stop_Request)(pointer_to_free))
}

func (t _Stop_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {

}

func (t _Stop_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {

}

func (t _Stop_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Stop_Request())
}

type CStop_Request = C.rosbag2_interfaces__srv__Stop_Request
type CStop_RequestSequence = C.rosbag2_interfaces__srv__Stop_Request__Sequence

func Stop_RequestSequenceToGo(goSlice *[]Stop_Request, cSlice CStop_RequestSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Stop_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Stop_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func Stop_RequestSequenceToC(cSlice *CStop_RequestSequence, goSlice []Stop_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Stop_Request)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__Stop_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Stop_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func Stop_RequestArrayToGo(goSlice []Stop_Request, cSlice []CStop_Request) {
	for i := 0; i < len(cSlice); i++ {
		Stop_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func Stop_RequestArrayToC(cSlice []CStop_Request, goSlice []Stop_Request) {
	for i := 0; i < len(goSlice); i++ {
		Stop_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
