// Code generated by ros2gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/toggle_paused.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("rosbag2_interfaces/TogglePaused", TogglePausedTypeSupport)
	<no value>.RegisterService("rosbag2_interfaces/srv/TogglePaused", TogglePausedTypeSupport)
}

type _TogglePausedTypeSupport struct {}

func (s _TogglePausedTypeSupport) Request() <no value>.MessageTypeSupport {
	return TogglePaused_RequestTypeSupport
}

func (s _TogglePausedTypeSupport) Response() <no value>.MessageTypeSupport {
	return TogglePaused_ResponseTypeSupport
}

func (s _TogglePausedTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__TogglePaused())
}

// Modifying this variable is undefined behavior.
var TogglePausedTypeSupport <no value>.ServiceTypeSupport = _TogglePausedTypeSupport{}

// TogglePausedClient wraps <no value>.Client to provide type safe helper
// functions
type TogglePausedClient struct {
	*<no value>.Client
}

// NewTogglePausedClient creates and returns a new client for the
// TogglePaused
func NewTogglePausedClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*TogglePausedClient, error) {
	client, err := node.NewClient(serviceName, TogglePausedTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &TogglePausedClient{client}, nil
}

func (s *TogglePausedClient) Send(ctx context.Context, req *TogglePaused_Request) (*TogglePaused_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*TogglePaused_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type TogglePausedServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s TogglePausedServiceResponseSender) SendResponse(resp *TogglePaused_Response) error {
	return s.sender.SendResponse(resp)
}

type TogglePausedServiceRequestHandler func(*<no value>.ServiceInfo, *TogglePaused_Request, TogglePausedServiceResponseSender)

// TogglePausedService wraps <no value>.Service to provide type safe helper
// functions
type TogglePausedService struct {
	*<no value>.Service
}

// NewTogglePausedService creates and returns a new service for the
// TogglePaused
func NewTogglePausedService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler TogglePausedServiceRequestHandler) (*TogglePausedService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*TogglePaused_Request)
		responseSender := TogglePausedServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, TogglePausedTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &TogglePausedService{service}, nil
}