// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/dynamic_land.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/DynamicLand", DynamicLandTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/DynamicLand", DynamicLandTypeSupport)
}

type _DynamicLandTypeSupport struct {}

func (s _DynamicLandTypeSupport) Request() <no value>.MessageTypeSupport {
	return DynamicLand_RequestTypeSupport
}

func (s _DynamicLandTypeSupport) Response() <no value>.MessageTypeSupport {
	return DynamicLand_ResponseTypeSupport
}

func (s _DynamicLandTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__DynamicLand())
}

// Modifying this variable is undefined behavior.
var DynamicLandTypeSupport <no value>.ServiceTypeSupport = _DynamicLandTypeSupport{}

// DynamicLandClient wraps <no value>.Client to provide type safe helper
// functions
type DynamicLandClient struct {
	*<no value>.Client
}

// NewDynamicLandClient creates and returns a new client for the
// DynamicLand
func NewDynamicLandClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*DynamicLandClient, error) {
	client, err := node.NewClient(serviceName, DynamicLandTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DynamicLandClient{client}, nil
}

func (s *DynamicLandClient) Send(ctx context.Context, req *DynamicLand_Request) (*DynamicLand_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*DynamicLand_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type DynamicLandServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s DynamicLandServiceResponseSender) SendResponse(resp *DynamicLand_Response) error {
	return s.sender.SendResponse(resp)
}

type DynamicLandServiceRequestHandler func(*<no value>.ServiceInfo, *DynamicLand_Request, DynamicLandServiceResponseSender)

// DynamicLandService wraps <no value>.Service to provide type safe helper
// functions
type DynamicLandService struct {
	*<no value>.Service
}

// NewDynamicLandService creates and returns a new service for the
// DynamicLand
func NewDynamicLandService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler DynamicLandServiceRequestHandler) (*DynamicLandService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*DynamicLand_Request)
		responseSender := DynamicLandServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, DynamicLandTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &DynamicLandService{service}, nil
}