// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/dynamic_follower.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/DynamicFollower", DynamicFollowerTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/DynamicFollower", DynamicFollowerTypeSupport)
}

type _DynamicFollowerTypeSupport struct {}

func (s _DynamicFollowerTypeSupport) Request() <no value>.MessageTypeSupport {
	return DynamicFollower_RequestTypeSupport
}

func (s _DynamicFollowerTypeSupport) Response() <no value>.MessageTypeSupport {
	return DynamicFollower_ResponseTypeSupport
}

func (s _DynamicFollowerTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__DynamicFollower())
}

// Modifying this variable is undefined behavior.
var DynamicFollowerTypeSupport <no value>.ServiceTypeSupport = _DynamicFollowerTypeSupport{}

// DynamicFollowerClient wraps <no value>.Client to provide type safe helper
// functions
type DynamicFollowerClient struct {
	*<no value>.Client
}

// NewDynamicFollowerClient creates and returns a new client for the
// DynamicFollower
func NewDynamicFollowerClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*DynamicFollowerClient, error) {
	client, err := node.NewClient(serviceName, DynamicFollowerTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DynamicFollowerClient{client}, nil
}

func (s *DynamicFollowerClient) Send(ctx context.Context, req *DynamicFollower_Request) (*DynamicFollower_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*DynamicFollower_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type DynamicFollowerServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s DynamicFollowerServiceResponseSender) SendResponse(resp *DynamicFollower_Response) error {
	return s.sender.SendResponse(resp)
}

type DynamicFollowerServiceRequestHandler func(*<no value>.ServiceInfo, *DynamicFollower_Request, DynamicFollowerServiceResponseSender)

// DynamicFollowerService wraps <no value>.Service to provide type safe helper
// functions
type DynamicFollowerService struct {
	*<no value>.Service
}

// NewDynamicFollowerService creates and returns a new service for the
// DynamicFollower
func NewDynamicFollowerService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler DynamicFollowerServiceRequestHandler) (*DynamicFollowerService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*DynamicFollower_Request)
		responseSender := DynamicFollowerServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, DynamicFollowerTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &DynamicFollowerService{service}, nil
}