// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/geopath_to_path.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/GeopathToPath", GeopathToPathTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/GeopathToPath", GeopathToPathTypeSupport)
}

type _GeopathToPathTypeSupport struct {}

func (s _GeopathToPathTypeSupport) Request() <no value>.MessageTypeSupport {
	return GeopathToPath_RequestTypeSupport
}

func (s _GeopathToPathTypeSupport) Response() <no value>.MessageTypeSupport {
	return GeopathToPath_ResponseTypeSupport
}

func (s _GeopathToPathTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__GeopathToPath())
}

// Modifying this variable is undefined behavior.
var GeopathToPathTypeSupport <no value>.ServiceTypeSupport = _GeopathToPathTypeSupport{}

// GeopathToPathClient wraps <no value>.Client to provide type safe helper
// functions
type GeopathToPathClient struct {
	*<no value>.Client
}

// NewGeopathToPathClient creates and returns a new client for the
// GeopathToPath
func NewGeopathToPathClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*GeopathToPathClient, error) {
	client, err := node.NewClient(serviceName, GeopathToPathTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GeopathToPathClient{client}, nil
}

func (s *GeopathToPathClient) Send(ctx context.Context, req *GeopathToPath_Request) (*GeopathToPath_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GeopathToPath_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GeopathToPathServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s GeopathToPathServiceResponseSender) SendResponse(resp *GeopathToPath_Response) error {
	return s.sender.SendResponse(resp)
}

type GeopathToPathServiceRequestHandler func(*<no value>.ServiceInfo, *GeopathToPath_Request, GeopathToPathServiceResponseSender)

// GeopathToPathService wraps <no value>.Service to provide type safe helper
// functions
type GeopathToPathService struct {
	*<no value>.Service
}

// NewGeopathToPathService creates and returns a new service for the
// GeopathToPath
func NewGeopathToPathService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler GeopathToPathServiceRequestHandler) (*GeopathToPathService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*GeopathToPath_Request)
		responseSender := GeopathToPathServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GeopathToPathTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GeopathToPathService{service}, nil
}