// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/list_control_modes.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/ListControlModes", ListControlModesTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/ListControlModes", ListControlModesTypeSupport)
}

type _ListControlModesTypeSupport struct {}

func (s _ListControlModesTypeSupport) Request() <no value>.MessageTypeSupport {
	return ListControlModes_RequestTypeSupport
}

func (s _ListControlModesTypeSupport) Response() <no value>.MessageTypeSupport {
	return ListControlModes_ResponseTypeSupport
}

func (s _ListControlModesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__ListControlModes())
}

// Modifying this variable is undefined behavior.
var ListControlModesTypeSupport <no value>.ServiceTypeSupport = _ListControlModesTypeSupport{}

// ListControlModesClient wraps <no value>.Client to provide type safe helper
// functions
type ListControlModesClient struct {
	*<no value>.Client
}

// NewListControlModesClient creates and returns a new client for the
// ListControlModes
func NewListControlModesClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*ListControlModesClient, error) {
	client, err := node.NewClient(serviceName, ListControlModesTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListControlModesClient{client}, nil
}

func (s *ListControlModesClient) Send(ctx context.Context, req *ListControlModes_Request) (*ListControlModes_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ListControlModes_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ListControlModesServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s ListControlModesServiceResponseSender) SendResponse(resp *ListControlModes_Response) error {
	return s.sender.SendResponse(resp)
}

type ListControlModesServiceRequestHandler func(*<no value>.ServiceInfo, *ListControlModes_Request, ListControlModesServiceResponseSender)

// ListControlModesService wraps <no value>.Service to provide type safe helper
// functions
type ListControlModesService struct {
	*<no value>.Service
}

// NewListControlModesService creates and returns a new service for the
// ListControlModes
func NewListControlModesService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler ListControlModesServiceRequestHandler) (*ListControlModesService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*ListControlModes_Request)
		responseSender := ListControlModesServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ListControlModesTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ListControlModesService{service}, nil
}