// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/package_pick_up.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/PackagePickUp", PackagePickUpTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/PackagePickUp", PackagePickUpTypeSupport)
}

type _PackagePickUpTypeSupport struct {}

func (s _PackagePickUpTypeSupport) Request() <no value>.MessageTypeSupport {
	return PackagePickUp_RequestTypeSupport
}

func (s _PackagePickUpTypeSupport) Response() <no value>.MessageTypeSupport {
	return PackagePickUp_ResponseTypeSupport
}

func (s _PackagePickUpTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__PackagePickUp())
}

// Modifying this variable is undefined behavior.
var PackagePickUpTypeSupport <no value>.ServiceTypeSupport = _PackagePickUpTypeSupport{}

// PackagePickUpClient wraps <no value>.Client to provide type safe helper
// functions
type PackagePickUpClient struct {
	*<no value>.Client
}

// NewPackagePickUpClient creates and returns a new client for the
// PackagePickUp
func NewPackagePickUpClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*PackagePickUpClient, error) {
	client, err := node.NewClient(serviceName, PackagePickUpTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PackagePickUpClient{client}, nil
}

func (s *PackagePickUpClient) Send(ctx context.Context, req *PackagePickUp_Request) (*PackagePickUp_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*PackagePickUp_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type PackagePickUpServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s PackagePickUpServiceResponseSender) SendResponse(resp *PackagePickUp_Response) error {
	return s.sender.SendResponse(resp)
}

type PackagePickUpServiceRequestHandler func(*<no value>.ServiceInfo, *PackagePickUp_Request, PackagePickUpServiceResponseSender)

// PackagePickUpService wraps <no value>.Service to provide type safe helper
// functions
type PackagePickUpService struct {
	*<no value>.Service
}

// NewPackagePickUpService creates and returns a new service for the
// PackagePickUp
func NewPackagePickUpService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler PackagePickUpServiceRequestHandler) (*PackagePickUpService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*PackagePickUp_Request)
		responseSender := PackagePickUpServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, PackagePickUpTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &PackagePickUpService{service}, nil
}