// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/package_un_pick.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/PackageUnPick", PackageUnPickTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/PackageUnPick", PackageUnPickTypeSupport)
}

type _PackageUnPickTypeSupport struct {}

func (s _PackageUnPickTypeSupport) Request() <no value>.MessageTypeSupport {
	return PackageUnPick_RequestTypeSupport
}

func (s _PackageUnPickTypeSupport) Response() <no value>.MessageTypeSupport {
	return PackageUnPick_ResponseTypeSupport
}

func (s _PackageUnPickTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__PackageUnPick())
}

// Modifying this variable is undefined behavior.
var PackageUnPickTypeSupport <no value>.ServiceTypeSupport = _PackageUnPickTypeSupport{}

// PackageUnPickClient wraps <no value>.Client to provide type safe helper
// functions
type PackageUnPickClient struct {
	*<no value>.Client
}

// NewPackageUnPickClient creates and returns a new client for the
// PackageUnPick
func NewPackageUnPickClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*PackageUnPickClient, error) {
	client, err := node.NewClient(serviceName, PackageUnPickTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PackageUnPickClient{client}, nil
}

func (s *PackageUnPickClient) Send(ctx context.Context, req *PackageUnPick_Request) (*PackageUnPick_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*PackageUnPick_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type PackageUnPickServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s PackageUnPickServiceResponseSender) SendResponse(resp *PackageUnPick_Response) error {
	return s.sender.SendResponse(resp)
}

type PackageUnPickServiceRequestHandler func(*<no value>.ServiceInfo, *PackageUnPick_Request, PackageUnPickServiceResponseSender)

// PackageUnPickService wraps <no value>.Service to provide type safe helper
// functions
type PackageUnPickService struct {
	*<no value>.Service
}

// NewPackageUnPickService creates and returns a new service for the
// PackageUnPick
func NewPackageUnPickService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler PackageUnPickServiceRequestHandler) (*PackageUnPickService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*PackageUnPick_Request)
		responseSender := PackageUnPickServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, PackageUnPickTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &PackageUnPickService{service}, nil
}