// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/set_geozone.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/SetGeozone", SetGeozoneTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/SetGeozone", SetGeozoneTypeSupport)
}

type _SetGeozoneTypeSupport struct {}

func (s _SetGeozoneTypeSupport) Request() <no value>.MessageTypeSupport {
	return SetGeozone_RequestTypeSupport
}

func (s _SetGeozoneTypeSupport) Response() <no value>.MessageTypeSupport {
	return SetGeozone_ResponseTypeSupport
}

func (s _SetGeozoneTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__SetGeozone())
}

// Modifying this variable is undefined behavior.
var SetGeozoneTypeSupport <no value>.ServiceTypeSupport = _SetGeozoneTypeSupport{}

// SetGeozoneClient wraps <no value>.Client to provide type safe helper
// functions
type SetGeozoneClient struct {
	*<no value>.Client
}

// NewSetGeozoneClient creates and returns a new client for the
// SetGeozone
func NewSetGeozoneClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*SetGeozoneClient, error) {
	client, err := node.NewClient(serviceName, SetGeozoneTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetGeozoneClient{client}, nil
}

func (s *SetGeozoneClient) Send(ctx context.Context, req *SetGeozone_Request) (*SetGeozone_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetGeozone_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetGeozoneServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s SetGeozoneServiceResponseSender) SendResponse(resp *SetGeozone_Response) error {
	return s.sender.SendResponse(resp)
}

type SetGeozoneServiceRequestHandler func(*<no value>.ServiceInfo, *SetGeozone_Request, SetGeozoneServiceResponseSender)

// SetGeozoneService wraps <no value>.Service to provide type safe helper
// functions
type SetGeozoneService struct {
	*<no value>.Service
}

// NewSetGeozoneService creates and returns a new service for the
// SetGeozone
func NewSetGeozoneService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler SetGeozoneServiceRequestHandler) (*SetGeozoneService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*SetGeozone_Request)
		responseSender := SetGeozoneServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetGeozoneTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetGeozoneService{service}, nil
}