// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/set_platform_state_machine_event.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/SetPlatformStateMachineEvent", SetPlatformStateMachineEventTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/SetPlatformStateMachineEvent", SetPlatformStateMachineEventTypeSupport)
}

type _SetPlatformStateMachineEventTypeSupport struct {}

func (s _SetPlatformStateMachineEventTypeSupport) Request() <no value>.MessageTypeSupport {
	return SetPlatformStateMachineEvent_RequestTypeSupport
}

func (s _SetPlatformStateMachineEventTypeSupport) Response() <no value>.MessageTypeSupport {
	return SetPlatformStateMachineEvent_ResponseTypeSupport
}

func (s _SetPlatformStateMachineEventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__SetPlatformStateMachineEvent())
}

// Modifying this variable is undefined behavior.
var SetPlatformStateMachineEventTypeSupport <no value>.ServiceTypeSupport = _SetPlatformStateMachineEventTypeSupport{}

// SetPlatformStateMachineEventClient wraps <no value>.Client to provide type safe helper
// functions
type SetPlatformStateMachineEventClient struct {
	*<no value>.Client
}

// NewSetPlatformStateMachineEventClient creates and returns a new client for the
// SetPlatformStateMachineEvent
func NewSetPlatformStateMachineEventClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*SetPlatformStateMachineEventClient, error) {
	client, err := node.NewClient(serviceName, SetPlatformStateMachineEventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetPlatformStateMachineEventClient{client}, nil
}

func (s *SetPlatformStateMachineEventClient) Send(ctx context.Context, req *SetPlatformStateMachineEvent_Request) (*SetPlatformStateMachineEvent_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetPlatformStateMachineEvent_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetPlatformStateMachineEventServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s SetPlatformStateMachineEventServiceResponseSender) SendResponse(resp *SetPlatformStateMachineEvent_Response) error {
	return s.sender.SendResponse(resp)
}

type SetPlatformStateMachineEventServiceRequestHandler func(*<no value>.ServiceInfo, *SetPlatformStateMachineEvent_Request, SetPlatformStateMachineEventServiceResponseSender)

// SetPlatformStateMachineEventService wraps <no value>.Service to provide type safe helper
// functions
type SetPlatformStateMachineEventService struct {
	*<no value>.Service
}

// NewSetPlatformStateMachineEventService creates and returns a new service for the
// SetPlatformStateMachineEvent
func NewSetPlatformStateMachineEventService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler SetPlatformStateMachineEventServiceRequestHandler) (*SetPlatformStateMachineEventService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*SetPlatformStateMachineEvent_Request)
		responseSender := SetPlatformStateMachineEventServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetPlatformStateMachineEventTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetPlatformStateMachineEventService{service}, nil
}