// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/set_speed.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/SetSpeed", SetSpeedTypeSupport)
	<no value>.RegisterService("as2_msgs/srv/SetSpeed", SetSpeedTypeSupport)
}

type _SetSpeedTypeSupport struct {}

func (s _SetSpeedTypeSupport) Request() <no value>.MessageTypeSupport {
	return SetSpeed_RequestTypeSupport
}

func (s _SetSpeedTypeSupport) Response() <no value>.MessageTypeSupport {
	return SetSpeed_ResponseTypeSupport
}

func (s _SetSpeedTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__SetSpeed())
}

// Modifying this variable is undefined behavior.
var SetSpeedTypeSupport <no value>.ServiceTypeSupport = _SetSpeedTypeSupport{}

// SetSpeedClient wraps <no value>.Client to provide type safe helper
// functions
type SetSpeedClient struct {
	*<no value>.Client
}

// NewSetSpeedClient creates and returns a new client for the
// SetSpeed
func NewSetSpeedClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*SetSpeedClient, error) {
	client, err := node.NewClient(serviceName, SetSpeedTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetSpeedClient{client}, nil
}

func (s *SetSpeedClient) Send(ctx context.Context, req *SetSpeed_Request) (*SetSpeed_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetSpeed_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetSpeedServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s SetSpeedServiceResponseSender) SendResponse(resp *SetSpeed_Response) error {
	return s.sender.SendResponse(resp)
}

type SetSpeedServiceRequestHandler func(*<no value>.ServiceInfo, *SetSpeed_Request, SetSpeedServiceResponseSender)

// SetSpeedService wraps <no value>.Service to provide type safe helper
// functions
type SetSpeedService struct {
	*<no value>.Service
}

// NewSetSpeedService creates and returns a new service for the
// SetSpeed
func NewSetSpeedService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler SetSpeedServiceRequestHandler) (*SetSpeedService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*SetSpeed_Request)
		responseSender := SetSpeedServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetSpeedTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetSpeedService{service}, nil
}