// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/detect_aruco_markers.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/DetectArucoMarkers_SendGoal", DetectArucoMarkers_SendGoalTypeSupport)
	<no value>.RegisterService("as2_msgs/action/DetectArucoMarkers_SendGoal", DetectArucoMarkers_SendGoalTypeSupport)
}

type _DetectArucoMarkers_SendGoalTypeSupport struct {}

func (s _DetectArucoMarkers_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return DetectArucoMarkers_SendGoal_RequestTypeSupport
}

func (s _DetectArucoMarkers_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return DetectArucoMarkers_SendGoal_ResponseTypeSupport
}

func (s _DetectArucoMarkers_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__DetectArucoMarkers_SendGoal())
}

// Modifying this variable is undefined behavior.
var DetectArucoMarkers_SendGoalTypeSupport <no value>.ServiceTypeSupport = _DetectArucoMarkers_SendGoalTypeSupport{}

// DetectArucoMarkers_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type DetectArucoMarkers_SendGoalClient struct {
	*<no value>.Client
}

// NewDetectArucoMarkers_SendGoalClient creates and returns a new client for the
// DetectArucoMarkers_SendGoal
func NewDetectArucoMarkers_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*DetectArucoMarkers_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, DetectArucoMarkers_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DetectArucoMarkers_SendGoalClient{client}, nil
}

func (s *DetectArucoMarkers_SendGoalClient) Send(ctx context.Context, req *DetectArucoMarkers_SendGoal_Request) (*DetectArucoMarkers_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*DetectArucoMarkers_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type DetectArucoMarkers_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s DetectArucoMarkers_SendGoalServiceResponseSender) SendResponse(resp *DetectArucoMarkers_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type DetectArucoMarkers_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *DetectArucoMarkers_SendGoal_Request, DetectArucoMarkers_SendGoalServiceResponseSender)

// DetectArucoMarkers_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type DetectArucoMarkers_SendGoalService struct {
	*<no value>.Service
}

// NewDetectArucoMarkers_SendGoalService creates and returns a new service for the
// DetectArucoMarkers_SendGoal
func NewDetectArucoMarkers_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler DetectArucoMarkers_SendGoalServiceRequestHandler) (*DetectArucoMarkers_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*DetectArucoMarkers_SendGoal_Request)
		responseSender := DetectArucoMarkers_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, DetectArucoMarkers_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &DetectArucoMarkers_SendGoalService{service}, nil
}