// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/follow_reference.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/FollowReference_SendGoal", FollowReference_SendGoalTypeSupport)
	<no value>.RegisterService("as2_msgs/action/FollowReference_SendGoal", FollowReference_SendGoalTypeSupport)
}

type _FollowReference_SendGoalTypeSupport struct {}

func (s _FollowReference_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return FollowReference_SendGoal_RequestTypeSupport
}

func (s _FollowReference_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return FollowReference_SendGoal_ResponseTypeSupport
}

func (s _FollowReference_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__FollowReference_SendGoal())
}

// Modifying this variable is undefined behavior.
var FollowReference_SendGoalTypeSupport <no value>.ServiceTypeSupport = _FollowReference_SendGoalTypeSupport{}

// FollowReference_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type FollowReference_SendGoalClient struct {
	*<no value>.Client
}

// NewFollowReference_SendGoalClient creates and returns a new client for the
// FollowReference_SendGoal
func NewFollowReference_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*FollowReference_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, FollowReference_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowReference_SendGoalClient{client}, nil
}

func (s *FollowReference_SendGoalClient) Send(ctx context.Context, req *FollowReference_SendGoal_Request) (*FollowReference_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FollowReference_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FollowReference_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s FollowReference_SendGoalServiceResponseSender) SendResponse(resp *FollowReference_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type FollowReference_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *FollowReference_SendGoal_Request, FollowReference_SendGoalServiceResponseSender)

// FollowReference_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type FollowReference_SendGoalService struct {
	*<no value>.Service
}

// NewFollowReference_SendGoalService creates and returns a new service for the
// FollowReference_SendGoal
func NewFollowReference_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler FollowReference_SendGoalServiceRequestHandler) (*FollowReference_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*FollowReference_SendGoal_Request)
		responseSender := FollowReference_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FollowReference_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FollowReference_SendGoalService{service}, nil
}