// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/follow_reference.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/FollowReference_GetResult", FollowReference_GetResultTypeSupport)
	<no value>.RegisterService("as2_msgs/action/FollowReference_GetResult", FollowReference_GetResultTypeSupport)
}

type _FollowReference_GetResultTypeSupport struct {}

func (s _FollowReference_GetResultTypeSupport) Request() <no value>.MessageTypeSupport {
	return FollowReference_GetResult_RequestTypeSupport
}

func (s _FollowReference_GetResultTypeSupport) Response() <no value>.MessageTypeSupport {
	return FollowReference_GetResult_ResponseTypeSupport
}

func (s _FollowReference_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__FollowReference_GetResult())
}

// Modifying this variable is undefined behavior.
var FollowReference_GetResultTypeSupport <no value>.ServiceTypeSupport = _FollowReference_GetResultTypeSupport{}

// FollowReference_GetResultClient wraps <no value>.Client to provide type safe helper
// functions
type FollowReference_GetResultClient struct {
	*<no value>.Client
}

// NewFollowReference_GetResultClient creates and returns a new client for the
// FollowReference_GetResult
func NewFollowReference_GetResultClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*FollowReference_GetResultClient, error) {
	client, err := node.NewClient(serviceName, FollowReference_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowReference_GetResultClient{client}, nil
}

func (s *FollowReference_GetResultClient) Send(ctx context.Context, req *FollowReference_GetResult_Request) (*FollowReference_GetResult_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FollowReference_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FollowReference_GetResultServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s FollowReference_GetResultServiceResponseSender) SendResponse(resp *FollowReference_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type FollowReference_GetResultServiceRequestHandler func(*<no value>.ServiceInfo, *FollowReference_GetResult_Request, FollowReference_GetResultServiceResponseSender)

// FollowReference_GetResultService wraps <no value>.Service to provide type safe helper
// functions
type FollowReference_GetResultService struct {
	*<no value>.Service
}

// NewFollowReference_GetResultService creates and returns a new service for the
// FollowReference_GetResult
func NewFollowReference_GetResultService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler FollowReference_GetResultServiceRequestHandler) (*FollowReference_GetResultService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*FollowReference_GetResult_Request)
		responseSender := FollowReference_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FollowReference_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FollowReference_GetResultService{service}, nil
}