// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/follow_path.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/FollowPath_SendGoal", FollowPath_SendGoalTypeSupport)
	<no value>.RegisterService("as2_msgs/action/FollowPath_SendGoal", FollowPath_SendGoalTypeSupport)
}

type _FollowPath_SendGoalTypeSupport struct {}

func (s _FollowPath_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return FollowPath_SendGoal_RequestTypeSupport
}

func (s _FollowPath_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return FollowPath_SendGoal_ResponseTypeSupport
}

func (s _FollowPath_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__FollowPath_SendGoal())
}

// Modifying this variable is undefined behavior.
var FollowPath_SendGoalTypeSupport <no value>.ServiceTypeSupport = _FollowPath_SendGoalTypeSupport{}

// FollowPath_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type FollowPath_SendGoalClient struct {
	*<no value>.Client
}

// NewFollowPath_SendGoalClient creates and returns a new client for the
// FollowPath_SendGoal
func NewFollowPath_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*FollowPath_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, FollowPath_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowPath_SendGoalClient{client}, nil
}

func (s *FollowPath_SendGoalClient) Send(ctx context.Context, req *FollowPath_SendGoal_Request) (*FollowPath_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FollowPath_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FollowPath_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s FollowPath_SendGoalServiceResponseSender) SendResponse(resp *FollowPath_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type FollowPath_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *FollowPath_SendGoal_Request, FollowPath_SendGoalServiceResponseSender)

// FollowPath_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type FollowPath_SendGoalService struct {
	*<no value>.Service
}

// NewFollowPath_SendGoalService creates and returns a new service for the
// FollowPath_SendGoal
func NewFollowPath_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler FollowPath_SendGoalServiceRequestHandler) (*FollowPath_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*FollowPath_SendGoal_Request)
		responseSender := FollowPath_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FollowPath_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FollowPath_SendGoalService{service}, nil
}