// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/follow_reference.h>
*/
import "C"

import (
	"context"
	"time"
	"unsafe"

	"github.com/okieraised/rclgo/humble"

	action_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/msg"
	action_msgs_srv "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/srv"
)

func init() {
	<no value>.RegisterAction("as2_msgs/FollowReference", FollowReferenceTypeSupport)
	<no value>.RegisterAction("as2_msgs/action/FollowReference", FollowReferenceTypeSupport)
}

type _FollowReferenceTypeSupport struct {}

func (s _FollowReferenceTypeSupport) Goal() <no value>.MessageTypeSupport {
	return FollowReference_GoalTypeSupport
}

func (s _FollowReferenceTypeSupport) SendGoal() <no value>.ServiceTypeSupport {
	return FollowReference_SendGoalTypeSupport
}

func (s _FollowReferenceTypeSupport) NewSendGoalResponse(accepted bool, stamp time.Duration) <no value>.Message {
	msg := NewFollowReference_SendGoal_Response()
	msg.Accepted = accepted
	secs := stamp.Truncate(time.Second)
	msg.Stamp.Sec = int32(secs)
	msg.Stamp.Nanosec = uint32(stamp - secs)
	return msg
}

func (s _FollowReferenceTypeSupport) Result() <no value>.MessageTypeSupport {
	return FollowReference_ResultTypeSupport
}

func (s _FollowReferenceTypeSupport) GetResult() <no value>.ServiceTypeSupport {
	return FollowReference_GetResultTypeSupport
}

func (s _FollowReferenceTypeSupport) NewGetResultResponse(status int8, result types.Message) <no value>.Message {
	msg := NewFollowReference_GetResult_Response()
	msg.Status = status
	if result == nil {
		msg.Result = *NewFollowReference_Result()
	} else {
		msg.Result = *result.(*FollowReference_Result)
	}
	return msg
}

func (s _FollowReferenceTypeSupport) CancelGoal() <no value>.ServiceTypeSupport {
	return action_msgs_srv.CancelGoalTypeSupport
}

func (s _FollowReferenceTypeSupport) Feedback() <no value>.MessageTypeSupport {
	return FollowReference_FeedbackTypeSupport
}

func (s _FollowReferenceTypeSupport) FeedbackMessage() <no value>.MessageTypeSupport {
	return FollowReference_FeedbackMessageTypeSupport
}

func (s _FollowReferenceTypeSupport) NewFeedbackMessage(goalID *<no value>.GoalID, feedback <no value>.Message) <no value>.Message {
	msg := NewFollowReference_FeedbackMessage()
	msg.GoalID.Uuid = *goalID
	msg.Feedback = *feedback.(*FollowReference_Feedback)
	return msg
}

func (s _FollowReferenceTypeSupport) GoalStatusArray() <no value>.MessageTypeSupport {
	return action_msgs_msg.GoalStatusArrayTypeSupport
}

func (s _FollowReferenceTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_action_type_support_handle__as2_msgs__action__FollowReference())
}

// Modifying this variable is undefined behavior.
var FollowReferenceTypeSupport <no value>.ActionTypeSupport = _FollowReferenceTypeSupport{}

type FollowReferenceFeedbackSender struct {
	sender <no value>.FeedbackSender
}

func (s *FollowReferenceFeedbackSender) Send(msg *FollowReference_Feedback) error {
	return s.sender.Send(msg)
}

type FollowReferenceGoalHandle struct{
	*<no value>.GoalHandle

	Description *FollowReference_Goal
}

func (g *FollowReferenceGoalHandle) Accept() (*FollowReferenceFeedbackSender, error) {
	s, err := g.GoalHandle.Accept()
	if err != nil {
		return nil, err
	}
	return &FollowReferenceFeedbackSender{*s}, nil
}

type FollowReferenceAction interface {
	ExecuteGoal(context.Context, *FollowReferenceGoalHandle) (*FollowReference_Result, error)
}

func NewFollowReferenceAction(
	executeGoal func(context.Context, *FollowReferenceGoalHandle) (*FollowReference_Result, error),
) FollowReferenceAction {
	return _FollowReferenceFuncAction(executeGoal)
}

type _FollowReferenceFuncAction func(context.Context, *FollowReferenceGoalHandle) (*FollowReference_Result, error)

func (a _FollowReferenceFuncAction) ExecuteGoal(
	ctx context.Context, goal *FollowReferenceGoalHandle,
) (*FollowReference_Result, error) {
	return a(ctx, goal)
}

type _FollowReferenceAction struct {
	action FollowReferenceAction
}

func (a _FollowReferenceAction) ExecuteGoal(ctx context.Context, handle *<no value>.GoalHandle) (<no value>.Message, error) {
	return a.action.ExecuteGoal(ctx, &FollowReferenceGoalHandle{
		GoalHandle:  handle,
		Description: handle.Description.(*FollowReference_Goal),
	})
}

func (a _FollowReferenceAction) TypeSupport() <no value>.ActionTypeSupport {
	return FollowReferenceTypeSupport
}

type FollowReferenceServer struct{
	*<no value>.ActionServer
}

func NewFollowReferenceServer(node *<no value>.Node, name string, action FollowReferenceAction, opts *<no value>.ActionServerOptions) (*FollowReferenceServer, error) {
	server, err := node.NewActionServer(name, _FollowReferenceAction{action}, opts)
	if err != nil {
		return nil, err
	}
	return &FollowReferenceServer{server}, nil
}

type FollowReferenceFeedbackHandler func(context.Context, *FollowReference_FeedbackMessage)

type FollowReferenceStatusHandler func(context.Context, *action_msgs_msg.GoalStatus)

type FollowReferenceClient struct{
	*<no value>.ActionClient
}

func NewFollowReferenceClient(node *<no value>.Node, name string, opts *<no value>.ActionClientOptions) (*FollowReferenceClient, error) {
	client, err := node.NewActionClient(name, FollowReferenceTypeSupport, opts)
	if err != nil {
		return nil, err
	}
	return &FollowReferenceClient{client}, nil
}

func (c *FollowReferenceClient) WatchGoal(ctx context.Context, goal *FollowReference_Goal, onFeedback FollowReferenceFeedbackHandler) (*FollowReference_GetResult_Response, *<no value>.GoalID, error) {
	var resp <no value>.Message
	var goalID *<no value>.GoalID
	var err error
	if onFeedback == nil {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, nil)
	} else {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, func(ctx context.Context, msg <no value>.Message) {
			onFeedback(ctx, msg.(*FollowReference_FeedbackMessage))
		})
	}
	if r, ok := resp.(*FollowReference_GetResult_Response); ok {
		return r, goalID, err
	}
	return nil, goalID, err
}

func (c *FollowReferenceClient) SendGoal(ctx context.Context, goal *FollowReference_Goal) (*FollowReference_SendGoal_Response, *<no value>.GoalID, error) {
	resp, id, err := c.ActionClient.SendGoal(ctx, goal)
	if r, ok := resp.(*FollowReference_SendGoal_Response); ok {
		return r, id, err
	}
	return nil, id, err
}

func (c *FollowReferenceClient) SendGoalRequest(ctx context.Context, request *FollowReference_SendGoal_Request) (*FollowReference_SendGoal_Response, error) {
	resp, err := c.ActionClient.SendGoalRequest(ctx, request)
	if r, ok := resp.(*FollowReference_SendGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *FollowReferenceClient) GetResult(ctx context.Context, goalID *<no value>.GoalID) (*FollowReference_GetResult_Response, error) {
	resp, err := c.ActionClient.GetResult(ctx, goalID)
	if r, ok := resp.(*FollowReference_GetResult_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *FollowReferenceClient) CancelGoal(ctx context.Context, request *action_msgs_srv.CancelGoal_Request) (*action_msgs_srv.CancelGoal_Response, error) {
	resp, err := c.ActionClient.CancelGoal(ctx, request)
	if r, ok := resp.(*action_msgs_srv.CancelGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *FollowReferenceClient) WatchFeedback(ctx context.Context, goalID *<no value>.GoalID, handler FollowReferenceFeedbackHandler) <-chan error {
	return c.ActionClient.WatchFeedback(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*FollowReference_FeedbackMessage))
	})
}

func (c *FollowReferenceClient) WatchStatus(ctx context.Context, goalID *<no value>.GoalID, handler FollowReferenceStatusHandler) <-chan error {
	return c.ActionClient.WatchStatus(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*action_msgs_msg.GoalStatus))
	})
}
