// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/generate_polynomial_trajectory.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/GeneratePolynomialTrajectory_GetResult", GeneratePolynomialTrajectory_GetResultTypeSupport)
	<no value>.RegisterService("as2_msgs/action/GeneratePolynomialTrajectory_GetResult", GeneratePolynomialTrajectory_GetResultTypeSupport)
}

type _GeneratePolynomialTrajectory_GetResultTypeSupport struct {}

func (s _GeneratePolynomialTrajectory_GetResultTypeSupport) Request() <no value>.MessageTypeSupport {
	return GeneratePolynomialTrajectory_GetResult_RequestTypeSupport
}

func (s _GeneratePolynomialTrajectory_GetResultTypeSupport) Response() <no value>.MessageTypeSupport {
	return GeneratePolynomialTrajectory_GetResult_ResponseTypeSupport
}

func (s _GeneratePolynomialTrajectory_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__GeneratePolynomialTrajectory_GetResult())
}

// Modifying this variable is undefined behavior.
var GeneratePolynomialTrajectory_GetResultTypeSupport <no value>.ServiceTypeSupport = _GeneratePolynomialTrajectory_GetResultTypeSupport{}

// GeneratePolynomialTrajectory_GetResultClient wraps <no value>.Client to provide type safe helper
// functions
type GeneratePolynomialTrajectory_GetResultClient struct {
	*<no value>.Client
}

// NewGeneratePolynomialTrajectory_GetResultClient creates and returns a new client for the
// GeneratePolynomialTrajectory_GetResult
func NewGeneratePolynomialTrajectory_GetResultClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*GeneratePolynomialTrajectory_GetResultClient, error) {
	client, err := node.NewClient(serviceName, GeneratePolynomialTrajectory_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GeneratePolynomialTrajectory_GetResultClient{client}, nil
}

func (s *GeneratePolynomialTrajectory_GetResultClient) Send(ctx context.Context, req *GeneratePolynomialTrajectory_GetResult_Request) (*GeneratePolynomialTrajectory_GetResult_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GeneratePolynomialTrajectory_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GeneratePolynomialTrajectory_GetResultServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s GeneratePolynomialTrajectory_GetResultServiceResponseSender) SendResponse(resp *GeneratePolynomialTrajectory_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type GeneratePolynomialTrajectory_GetResultServiceRequestHandler func(*<no value>.ServiceInfo, *GeneratePolynomialTrajectory_GetResult_Request, GeneratePolynomialTrajectory_GetResultServiceResponseSender)

// GeneratePolynomialTrajectory_GetResultService wraps <no value>.Service to provide type safe helper
// functions
type GeneratePolynomialTrajectory_GetResultService struct {
	*<no value>.Service
}

// NewGeneratePolynomialTrajectory_GetResultService creates and returns a new service for the
// GeneratePolynomialTrajectory_GetResult
func NewGeneratePolynomialTrajectory_GetResultService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler GeneratePolynomialTrajectory_GetResultServiceRequestHandler) (*GeneratePolynomialTrajectory_GetResultService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*GeneratePolynomialTrajectory_GetResult_Request)
		responseSender := GeneratePolynomialTrajectory_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GeneratePolynomialTrajectory_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GeneratePolynomialTrajectory_GetResultService{service}, nil
}