// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/generate_polynomial_trajectory.h>
*/
import "C"

import (
	"context"
	"time"
	"unsafe"

	"github.com/okieraised/rclgo/humble"

	action_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/msg"
	action_msgs_srv "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/srv"
)

func init() {
	<no value>.RegisterAction("as2_msgs/GeneratePolynomialTrajectory", GeneratePolynomialTrajectoryTypeSupport)
	<no value>.RegisterAction("as2_msgs/action/GeneratePolynomialTrajectory", GeneratePolynomialTrajectoryTypeSupport)
}

type _GeneratePolynomialTrajectoryTypeSupport struct {}

func (s _GeneratePolynomialTrajectoryTypeSupport) Goal() <no value>.MessageTypeSupport {
	return GeneratePolynomialTrajectory_GoalTypeSupport
}

func (s _GeneratePolynomialTrajectoryTypeSupport) SendGoal() <no value>.ServiceTypeSupport {
	return GeneratePolynomialTrajectory_SendGoalTypeSupport
}

func (s _GeneratePolynomialTrajectoryTypeSupport) NewSendGoalResponse(accepted bool, stamp time.Duration) <no value>.Message {
	msg := NewGeneratePolynomialTrajectory_SendGoal_Response()
	msg.Accepted = accepted
	secs := stamp.Truncate(time.Second)
	msg.Stamp.Sec = int32(secs)
	msg.Stamp.Nanosec = uint32(stamp - secs)
	return msg
}

func (s _GeneratePolynomialTrajectoryTypeSupport) Result() <no value>.MessageTypeSupport {
	return GeneratePolynomialTrajectory_ResultTypeSupport
}

func (s _GeneratePolynomialTrajectoryTypeSupport) GetResult() <no value>.ServiceTypeSupport {
	return GeneratePolynomialTrajectory_GetResultTypeSupport
}

func (s _GeneratePolynomialTrajectoryTypeSupport) NewGetResultResponse(status int8, result types.Message) <no value>.Message {
	msg := NewGeneratePolynomialTrajectory_GetResult_Response()
	msg.Status = status
	if result == nil {
		msg.Result = *NewGeneratePolynomialTrajectory_Result()
	} else {
		msg.Result = *result.(*GeneratePolynomialTrajectory_Result)
	}
	return msg
}

func (s _GeneratePolynomialTrajectoryTypeSupport) CancelGoal() <no value>.ServiceTypeSupport {
	return action_msgs_srv.CancelGoalTypeSupport
}

func (s _GeneratePolynomialTrajectoryTypeSupport) Feedback() <no value>.MessageTypeSupport {
	return GeneratePolynomialTrajectory_FeedbackTypeSupport
}

func (s _GeneratePolynomialTrajectoryTypeSupport) FeedbackMessage() <no value>.MessageTypeSupport {
	return GeneratePolynomialTrajectory_FeedbackMessageTypeSupport
}

func (s _GeneratePolynomialTrajectoryTypeSupport) NewFeedbackMessage(goalID *<no value>.GoalID, feedback <no value>.Message) <no value>.Message {
	msg := NewGeneratePolynomialTrajectory_FeedbackMessage()
	msg.GoalID.Uuid = *goalID
	msg.Feedback = *feedback.(*GeneratePolynomialTrajectory_Feedback)
	return msg
}

func (s _GeneratePolynomialTrajectoryTypeSupport) GoalStatusArray() <no value>.MessageTypeSupport {
	return action_msgs_msg.GoalStatusArrayTypeSupport
}

func (s _GeneratePolynomialTrajectoryTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_action_type_support_handle__as2_msgs__action__GeneratePolynomialTrajectory())
}

// Modifying this variable is undefined behavior.
var GeneratePolynomialTrajectoryTypeSupport <no value>.ActionTypeSupport = _GeneratePolynomialTrajectoryTypeSupport{}

type GeneratePolynomialTrajectoryFeedbackSender struct {
	sender <no value>.FeedbackSender
}

func (s *GeneratePolynomialTrajectoryFeedbackSender) Send(msg *GeneratePolynomialTrajectory_Feedback) error {
	return s.sender.Send(msg)
}

type GeneratePolynomialTrajectoryGoalHandle struct{
	*<no value>.GoalHandle

	Description *GeneratePolynomialTrajectory_Goal
}

func (g *GeneratePolynomialTrajectoryGoalHandle) Accept() (*GeneratePolynomialTrajectoryFeedbackSender, error) {
	s, err := g.GoalHandle.Accept()
	if err != nil {
		return nil, err
	}
	return &GeneratePolynomialTrajectoryFeedbackSender{*s}, nil
}

type GeneratePolynomialTrajectoryAction interface {
	ExecuteGoal(context.Context, *GeneratePolynomialTrajectoryGoalHandle) (*GeneratePolynomialTrajectory_Result, error)
}

func NewGeneratePolynomialTrajectoryAction(
	executeGoal func(context.Context, *GeneratePolynomialTrajectoryGoalHandle) (*GeneratePolynomialTrajectory_Result, error),
) GeneratePolynomialTrajectoryAction {
	return _GeneratePolynomialTrajectoryFuncAction(executeGoal)
}

type _GeneratePolynomialTrajectoryFuncAction func(context.Context, *GeneratePolynomialTrajectoryGoalHandle) (*GeneratePolynomialTrajectory_Result, error)

func (a _GeneratePolynomialTrajectoryFuncAction) ExecuteGoal(
	ctx context.Context, goal *GeneratePolynomialTrajectoryGoalHandle,
) (*GeneratePolynomialTrajectory_Result, error) {
	return a(ctx, goal)
}

type _GeneratePolynomialTrajectoryAction struct {
	action GeneratePolynomialTrajectoryAction
}

func (a _GeneratePolynomialTrajectoryAction) ExecuteGoal(ctx context.Context, handle *<no value>.GoalHandle) (<no value>.Message, error) {
	return a.action.ExecuteGoal(ctx, &GeneratePolynomialTrajectoryGoalHandle{
		GoalHandle:  handle,
		Description: handle.Description.(*GeneratePolynomialTrajectory_Goal),
	})
}

func (a _GeneratePolynomialTrajectoryAction) TypeSupport() <no value>.ActionTypeSupport {
	return GeneratePolynomialTrajectoryTypeSupport
}

type GeneratePolynomialTrajectoryServer struct{
	*<no value>.ActionServer
}

func NewGeneratePolynomialTrajectoryServer(node *<no value>.Node, name string, action GeneratePolynomialTrajectoryAction, opts *<no value>.ActionServerOptions) (*GeneratePolynomialTrajectoryServer, error) {
	server, err := node.NewActionServer(name, _GeneratePolynomialTrajectoryAction{action}, opts)
	if err != nil {
		return nil, err
	}
	return &GeneratePolynomialTrajectoryServer{server}, nil
}

type GeneratePolynomialTrajectoryFeedbackHandler func(context.Context, *GeneratePolynomialTrajectory_FeedbackMessage)

type GeneratePolynomialTrajectoryStatusHandler func(context.Context, *action_msgs_msg.GoalStatus)

type GeneratePolynomialTrajectoryClient struct{
	*<no value>.ActionClient
}

func NewGeneratePolynomialTrajectoryClient(node *<no value>.Node, name string, opts *<no value>.ActionClientOptions) (*GeneratePolynomialTrajectoryClient, error) {
	client, err := node.NewActionClient(name, GeneratePolynomialTrajectoryTypeSupport, opts)
	if err != nil {
		return nil, err
	}
	return &GeneratePolynomialTrajectoryClient{client}, nil
}

func (c *GeneratePolynomialTrajectoryClient) WatchGoal(ctx context.Context, goal *GeneratePolynomialTrajectory_Goal, onFeedback GeneratePolynomialTrajectoryFeedbackHandler) (*GeneratePolynomialTrajectory_GetResult_Response, *<no value>.GoalID, error) {
	var resp <no value>.Message
	var goalID *<no value>.GoalID
	var err error
	if onFeedback == nil {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, nil)
	} else {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, func(ctx context.Context, msg <no value>.Message) {
			onFeedback(ctx, msg.(*GeneratePolynomialTrajectory_FeedbackMessage))
		})
	}
	if r, ok := resp.(*GeneratePolynomialTrajectory_GetResult_Response); ok {
		return r, goalID, err
	}
	return nil, goalID, err
}

func (c *GeneratePolynomialTrajectoryClient) SendGoal(ctx context.Context, goal *GeneratePolynomialTrajectory_Goal) (*GeneratePolynomialTrajectory_SendGoal_Response, *<no value>.GoalID, error) {
	resp, id, err := c.ActionClient.SendGoal(ctx, goal)
	if r, ok := resp.(*GeneratePolynomialTrajectory_SendGoal_Response); ok {
		return r, id, err
	}
	return nil, id, err
}

func (c *GeneratePolynomialTrajectoryClient) SendGoalRequest(ctx context.Context, request *GeneratePolynomialTrajectory_SendGoal_Request) (*GeneratePolynomialTrajectory_SendGoal_Response, error) {
	resp, err := c.ActionClient.SendGoalRequest(ctx, request)
	if r, ok := resp.(*GeneratePolynomialTrajectory_SendGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *GeneratePolynomialTrajectoryClient) GetResult(ctx context.Context, goalID *<no value>.GoalID) (*GeneratePolynomialTrajectory_GetResult_Response, error) {
	resp, err := c.ActionClient.GetResult(ctx, goalID)
	if r, ok := resp.(*GeneratePolynomialTrajectory_GetResult_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *GeneratePolynomialTrajectoryClient) CancelGoal(ctx context.Context, request *action_msgs_srv.CancelGoal_Request) (*action_msgs_srv.CancelGoal_Response, error) {
	resp, err := c.ActionClient.CancelGoal(ctx, request)
	if r, ok := resp.(*action_msgs_srv.CancelGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *GeneratePolynomialTrajectoryClient) WatchFeedback(ctx context.Context, goalID *<no value>.GoalID, handler GeneratePolynomialTrajectoryFeedbackHandler) <-chan error {
	return c.ActionClient.WatchFeedback(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*GeneratePolynomialTrajectory_FeedbackMessage))
	})
}

func (c *GeneratePolynomialTrajectoryClient) WatchStatus(ctx context.Context, goalID *<no value>.GoalID, handler GeneratePolynomialTrajectoryStatusHandler) <-chan error {
	return c.ActionClient.WatchStatus(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*action_msgs_msg.GoalStatus))
	})
}
