// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/go_to_waypoint.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/GoToWaypoint_SendGoal", GoToWaypoint_SendGoalTypeSupport)
	<no value>.RegisterService("as2_msgs/action/GoToWaypoint_SendGoal", GoToWaypoint_SendGoalTypeSupport)
}

type _GoToWaypoint_SendGoalTypeSupport struct {}

func (s _GoToWaypoint_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return GoToWaypoint_SendGoal_RequestTypeSupport
}

func (s _GoToWaypoint_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return GoToWaypoint_SendGoal_ResponseTypeSupport
}

func (s _GoToWaypoint_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__GoToWaypoint_SendGoal())
}

// Modifying this variable is undefined behavior.
var GoToWaypoint_SendGoalTypeSupport <no value>.ServiceTypeSupport = _GoToWaypoint_SendGoalTypeSupport{}

// GoToWaypoint_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type GoToWaypoint_SendGoalClient struct {
	*<no value>.Client
}

// NewGoToWaypoint_SendGoalClient creates and returns a new client for the
// GoToWaypoint_SendGoal
func NewGoToWaypoint_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*GoToWaypoint_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, GoToWaypoint_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GoToWaypoint_SendGoalClient{client}, nil
}

func (s *GoToWaypoint_SendGoalClient) Send(ctx context.Context, req *GoToWaypoint_SendGoal_Request) (*GoToWaypoint_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GoToWaypoint_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GoToWaypoint_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s GoToWaypoint_SendGoalServiceResponseSender) SendResponse(resp *GoToWaypoint_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type GoToWaypoint_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *GoToWaypoint_SendGoal_Request, GoToWaypoint_SendGoalServiceResponseSender)

// GoToWaypoint_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type GoToWaypoint_SendGoalService struct {
	*<no value>.Service
}

// NewGoToWaypoint_SendGoalService creates and returns a new service for the
// GoToWaypoint_SendGoal
func NewGoToWaypoint_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler GoToWaypoint_SendGoalServiceRequestHandler) (*GoToWaypoint_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*GoToWaypoint_SendGoal_Request)
		responseSender := GoToWaypoint_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GoToWaypoint_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GoToWaypoint_SendGoalService{service}, nil
}