// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/go_to_waypoint.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/GoToWaypoint_GetResult", GoToWaypoint_GetResultTypeSupport)
	<no value>.RegisterService("as2_msgs/action/GoToWaypoint_GetResult", GoToWaypoint_GetResultTypeSupport)
}

type _GoToWaypoint_GetResultTypeSupport struct {}

func (s _GoToWaypoint_GetResultTypeSupport) Request() <no value>.MessageTypeSupport {
	return GoToWaypoint_GetResult_RequestTypeSupport
}

func (s _GoToWaypoint_GetResultTypeSupport) Response() <no value>.MessageTypeSupport {
	return GoToWaypoint_GetResult_ResponseTypeSupport
}

func (s _GoToWaypoint_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__GoToWaypoint_GetResult())
}

// Modifying this variable is undefined behavior.
var GoToWaypoint_GetResultTypeSupport <no value>.ServiceTypeSupport = _GoToWaypoint_GetResultTypeSupport{}

// GoToWaypoint_GetResultClient wraps <no value>.Client to provide type safe helper
// functions
type GoToWaypoint_GetResultClient struct {
	*<no value>.Client
}

// NewGoToWaypoint_GetResultClient creates and returns a new client for the
// GoToWaypoint_GetResult
func NewGoToWaypoint_GetResultClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*GoToWaypoint_GetResultClient, error) {
	client, err := node.NewClient(serviceName, GoToWaypoint_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GoToWaypoint_GetResultClient{client}, nil
}

func (s *GoToWaypoint_GetResultClient) Send(ctx context.Context, req *GoToWaypoint_GetResult_Request) (*GoToWaypoint_GetResult_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GoToWaypoint_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GoToWaypoint_GetResultServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s GoToWaypoint_GetResultServiceResponseSender) SendResponse(resp *GoToWaypoint_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type GoToWaypoint_GetResultServiceRequestHandler func(*<no value>.ServiceInfo, *GoToWaypoint_GetResult_Request, GoToWaypoint_GetResultServiceResponseSender)

// GoToWaypoint_GetResultService wraps <no value>.Service to provide type safe helper
// functions
type GoToWaypoint_GetResultService struct {
	*<no value>.Service
}

// NewGoToWaypoint_GetResultService creates and returns a new service for the
// GoToWaypoint_GetResult
func NewGoToWaypoint_GetResultService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler GoToWaypoint_GetResultServiceRequestHandler) (*GoToWaypoint_GetResultService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*GoToWaypoint_GetResult_Request)
		responseSender := GoToWaypoint_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GoToWaypoint_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GoToWaypoint_GetResultService{service}, nil
}