// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/land.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/Land_GetResult", Land_GetResultTypeSupport)
	<no value>.RegisterService("as2_msgs/action/Land_GetResult", Land_GetResultTypeSupport)
}

type _Land_GetResultTypeSupport struct {}

func (s _Land_GetResultTypeSupport) Request() <no value>.MessageTypeSupport {
	return Land_GetResult_RequestTypeSupport
}

func (s _Land_GetResultTypeSupport) Response() <no value>.MessageTypeSupport {
	return Land_GetResult_ResponseTypeSupport
}

func (s _Land_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__Land_GetResult())
}

// Modifying this variable is undefined behavior.
var Land_GetResultTypeSupport <no value>.ServiceTypeSupport = _Land_GetResultTypeSupport{}

// Land_GetResultClient wraps <no value>.Client to provide type safe helper
// functions
type Land_GetResultClient struct {
	*<no value>.Client
}

// NewLand_GetResultClient creates and returns a new client for the
// Land_GetResult
func NewLand_GetResultClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*Land_GetResultClient, error) {
	client, err := node.NewClient(serviceName, Land_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Land_GetResultClient{client}, nil
}

func (s *Land_GetResultClient) Send(ctx context.Context, req *Land_GetResult_Request) (*Land_GetResult_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Land_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type Land_GetResultServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s Land_GetResultServiceResponseSender) SendResponse(resp *Land_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type Land_GetResultServiceRequestHandler func(*<no value>.ServiceInfo, *Land_GetResult_Request, Land_GetResultServiceResponseSender)

// Land_GetResultService wraps <no value>.Service to provide type safe helper
// functions
type Land_GetResultService struct {
	*<no value>.Service
}

// NewLand_GetResultService creates and returns a new service for the
// Land_GetResult
func NewLand_GetResultService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler Land_GetResultServiceRequestHandler) (*Land_GetResultService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*Land_GetResult_Request)
		responseSender := Land_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, Land_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &Land_GetResultService{service}, nil
}