// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/land.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/Land_SendGoal", Land_SendGoalTypeSupport)
	<no value>.RegisterService("as2_msgs/action/Land_SendGoal", Land_SendGoalTypeSupport)
}

type _Land_SendGoalTypeSupport struct {}

func (s _Land_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return Land_SendGoal_RequestTypeSupport
}

func (s _Land_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return Land_SendGoal_ResponseTypeSupport
}

func (s _Land_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__Land_SendGoal())
}

// Modifying this variable is undefined behavior.
var Land_SendGoalTypeSupport <no value>.ServiceTypeSupport = _Land_SendGoalTypeSupport{}

// Land_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type Land_SendGoalClient struct {
	*<no value>.Client
}

// NewLand_SendGoalClient creates and returns a new client for the
// Land_SendGoal
func NewLand_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*Land_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, Land_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Land_SendGoalClient{client}, nil
}

func (s *Land_SendGoalClient) Send(ctx context.Context, req *Land_SendGoal_Request) (*Land_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Land_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type Land_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s Land_SendGoalServiceResponseSender) SendResponse(resp *Land_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type Land_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *Land_SendGoal_Request, Land_SendGoalServiceResponseSender)

// Land_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type Land_SendGoalService struct {
	*<no value>.Service
}

// NewLand_SendGoalService creates and returns a new service for the
// Land_SendGoal
func NewLand_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler Land_SendGoalServiceRequestHandler) (*Land_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*Land_SendGoal_Request)
		responseSender := Land_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, Land_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &Land_SendGoalService{service}, nil
}