// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/land.h>
*/
import "C"

import (
	"context"
	"time"
	"unsafe"

	"github.com/okieraised/rclgo/humble"

	action_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/msg"
	action_msgs_srv "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/srv"
)

func init() {
	<no value>.RegisterAction("as2_msgs/Land", LandTypeSupport)
	<no value>.RegisterAction("as2_msgs/action/Land", LandTypeSupport)
}

type _LandTypeSupport struct {}

func (s _LandTypeSupport) Goal() <no value>.MessageTypeSupport {
	return Land_GoalTypeSupport
}

func (s _LandTypeSupport) SendGoal() <no value>.ServiceTypeSupport {
	return Land_SendGoalTypeSupport
}

func (s _LandTypeSupport) NewSendGoalResponse(accepted bool, stamp time.Duration) <no value>.Message {
	msg := NewLand_SendGoal_Response()
	msg.Accepted = accepted
	secs := stamp.Truncate(time.Second)
	msg.Stamp.Sec = int32(secs)
	msg.Stamp.Nanosec = uint32(stamp - secs)
	return msg
}

func (s _LandTypeSupport) Result() <no value>.MessageTypeSupport {
	return Land_ResultTypeSupport
}

func (s _LandTypeSupport) GetResult() <no value>.ServiceTypeSupport {
	return Land_GetResultTypeSupport
}

func (s _LandTypeSupport) NewGetResultResponse(status int8, result types.Message) <no value>.Message {
	msg := NewLand_GetResult_Response()
	msg.Status = status
	if result == nil {
		msg.Result = *NewLand_Result()
	} else {
		msg.Result = *result.(*Land_Result)
	}
	return msg
}

func (s _LandTypeSupport) CancelGoal() <no value>.ServiceTypeSupport {
	return action_msgs_srv.CancelGoalTypeSupport
}

func (s _LandTypeSupport) Feedback() <no value>.MessageTypeSupport {
	return Land_FeedbackTypeSupport
}

func (s _LandTypeSupport) FeedbackMessage() <no value>.MessageTypeSupport {
	return Land_FeedbackMessageTypeSupport
}

func (s _LandTypeSupport) NewFeedbackMessage(goalID *<no value>.GoalID, feedback <no value>.Message) <no value>.Message {
	msg := NewLand_FeedbackMessage()
	msg.GoalID.Uuid = *goalID
	msg.Feedback = *feedback.(*Land_Feedback)
	return msg
}

func (s _LandTypeSupport) GoalStatusArray() <no value>.MessageTypeSupport {
	return action_msgs_msg.GoalStatusArrayTypeSupport
}

func (s _LandTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_action_type_support_handle__as2_msgs__action__Land())
}

// Modifying this variable is undefined behavior.
var LandTypeSupport <no value>.ActionTypeSupport = _LandTypeSupport{}

type LandFeedbackSender struct {
	sender <no value>.FeedbackSender
}

func (s *LandFeedbackSender) Send(msg *Land_Feedback) error {
	return s.sender.Send(msg)
}

type LandGoalHandle struct{
	*<no value>.GoalHandle

	Description *Land_Goal
}

func (g *LandGoalHandle) Accept() (*LandFeedbackSender, error) {
	s, err := g.GoalHandle.Accept()
	if err != nil {
		return nil, err
	}
	return &LandFeedbackSender{*s}, nil
}

type LandAction interface {
	ExecuteGoal(context.Context, *LandGoalHandle) (*Land_Result, error)
}

func NewLandAction(
	executeGoal func(context.Context, *LandGoalHandle) (*Land_Result, error),
) LandAction {
	return _LandFuncAction(executeGoal)
}

type _LandFuncAction func(context.Context, *LandGoalHandle) (*Land_Result, error)

func (a _LandFuncAction) ExecuteGoal(
	ctx context.Context, goal *LandGoalHandle,
) (*Land_Result, error) {
	return a(ctx, goal)
}

type _LandAction struct {
	action LandAction
}

func (a _LandAction) ExecuteGoal(ctx context.Context, handle *<no value>.GoalHandle) (<no value>.Message, error) {
	return a.action.ExecuteGoal(ctx, &LandGoalHandle{
		GoalHandle:  handle,
		Description: handle.Description.(*Land_Goal),
	})
}

func (a _LandAction) TypeSupport() <no value>.ActionTypeSupport {
	return LandTypeSupport
}

type LandServer struct{
	*<no value>.ActionServer
}

func NewLandServer(node *<no value>.Node, name string, action LandAction, opts *<no value>.ActionServerOptions) (*LandServer, error) {
	server, err := node.NewActionServer(name, _LandAction{action}, opts)
	if err != nil {
		return nil, err
	}
	return &LandServer{server}, nil
}

type LandFeedbackHandler func(context.Context, *Land_FeedbackMessage)

type LandStatusHandler func(context.Context, *action_msgs_msg.GoalStatus)

type LandClient struct{
	*<no value>.ActionClient
}

func NewLandClient(node *<no value>.Node, name string, opts *<no value>.ActionClientOptions) (*LandClient, error) {
	client, err := node.NewActionClient(name, LandTypeSupport, opts)
	if err != nil {
		return nil, err
	}
	return &LandClient{client}, nil
}

func (c *LandClient) WatchGoal(ctx context.Context, goal *Land_Goal, onFeedback LandFeedbackHandler) (*Land_GetResult_Response, *<no value>.GoalID, error) {
	var resp <no value>.Message
	var goalID *<no value>.GoalID
	var err error
	if onFeedback == nil {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, nil)
	} else {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, func(ctx context.Context, msg <no value>.Message) {
			onFeedback(ctx, msg.(*Land_FeedbackMessage))
		})
	}
	if r, ok := resp.(*Land_GetResult_Response); ok {
		return r, goalID, err
	}
	return nil, goalID, err
}

func (c *LandClient) SendGoal(ctx context.Context, goal *Land_Goal) (*Land_SendGoal_Response, *<no value>.GoalID, error) {
	resp, id, err := c.ActionClient.SendGoal(ctx, goal)
	if r, ok := resp.(*Land_SendGoal_Response); ok {
		return r, id, err
	}
	return nil, id, err
}

func (c *LandClient) SendGoalRequest(ctx context.Context, request *Land_SendGoal_Request) (*Land_SendGoal_Response, error) {
	resp, err := c.ActionClient.SendGoalRequest(ctx, request)
	if r, ok := resp.(*Land_SendGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *LandClient) GetResult(ctx context.Context, goalID *<no value>.GoalID) (*Land_GetResult_Response, error) {
	resp, err := c.ActionClient.GetResult(ctx, goalID)
	if r, ok := resp.(*Land_GetResult_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *LandClient) CancelGoal(ctx context.Context, request *action_msgs_srv.CancelGoal_Request) (*action_msgs_srv.CancelGoal_Response, error) {
	resp, err := c.ActionClient.CancelGoal(ctx, request)
	if r, ok := resp.(*action_msgs_srv.CancelGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *LandClient) WatchFeedback(ctx context.Context, goalID *<no value>.GoalID, handler LandFeedbackHandler) <-chan error {
	return c.ActionClient.WatchFeedback(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*Land_FeedbackMessage))
	})
}

func (c *LandClient) WatchStatus(ctx context.Context, goalID *<no value>.GoalID, handler LandStatusHandler) <-chan error {
	return c.ActionClient.WatchStatus(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*action_msgs_msg.GoalStatus))
	})
}
