// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/navigate_to_point.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/NavigateToPoint_SendGoal", NavigateToPoint_SendGoalTypeSupport)
	<no value>.RegisterService("as2_msgs/action/NavigateToPoint_SendGoal", NavigateToPoint_SendGoalTypeSupport)
}

type _NavigateToPoint_SendGoalTypeSupport struct {}

func (s _NavigateToPoint_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return NavigateToPoint_SendGoal_RequestTypeSupport
}

func (s _NavigateToPoint_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return NavigateToPoint_SendGoal_ResponseTypeSupport
}

func (s _NavigateToPoint_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__NavigateToPoint_SendGoal())
}

// Modifying this variable is undefined behavior.
var NavigateToPoint_SendGoalTypeSupport <no value>.ServiceTypeSupport = _NavigateToPoint_SendGoalTypeSupport{}

// NavigateToPoint_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type NavigateToPoint_SendGoalClient struct {
	*<no value>.Client
}

// NewNavigateToPoint_SendGoalClient creates and returns a new client for the
// NavigateToPoint_SendGoal
func NewNavigateToPoint_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*NavigateToPoint_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, NavigateToPoint_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &NavigateToPoint_SendGoalClient{client}, nil
}

func (s *NavigateToPoint_SendGoalClient) Send(ctx context.Context, req *NavigateToPoint_SendGoal_Request) (*NavigateToPoint_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*NavigateToPoint_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type NavigateToPoint_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s NavigateToPoint_SendGoalServiceResponseSender) SendResponse(resp *NavigateToPoint_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type NavigateToPoint_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *NavigateToPoint_SendGoal_Request, NavigateToPoint_SendGoalServiceResponseSender)

// NavigateToPoint_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type NavigateToPoint_SendGoalService struct {
	*<no value>.Service
}

// NewNavigateToPoint_SendGoalService creates and returns a new service for the
// NavigateToPoint_SendGoal
func NewNavigateToPoint_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler NavigateToPoint_SendGoalServiceRequestHandler) (*NavigateToPoint_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*NavigateToPoint_SendGoal_Request)
		responseSender := NavigateToPoint_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, NavigateToPoint_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &NavigateToPoint_SendGoalService{service}, nil
}