// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/point_gimbal.h>
*/
import "C"

import (
	"context"
	"time"
	"unsafe"

	"github.com/okieraised/rclgo/humble"

	action_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/msg"
	action_msgs_srv "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/srv"
)

func init() {
	<no value>.RegisterAction("as2_msgs/PointGimbal", PointGimbalTypeSupport)
	<no value>.RegisterAction("as2_msgs/action/PointGimbal", PointGimbalTypeSupport)
}

type _PointGimbalTypeSupport struct {}

func (s _PointGimbalTypeSupport) Goal() <no value>.MessageTypeSupport {
	return PointGimbal_GoalTypeSupport
}

func (s _PointGimbalTypeSupport) SendGoal() <no value>.ServiceTypeSupport {
	return PointGimbal_SendGoalTypeSupport
}

func (s _PointGimbalTypeSupport) NewSendGoalResponse(accepted bool, stamp time.Duration) <no value>.Message {
	msg := NewPointGimbal_SendGoal_Response()
	msg.Accepted = accepted
	secs := stamp.Truncate(time.Second)
	msg.Stamp.Sec = int32(secs)
	msg.Stamp.Nanosec = uint32(stamp - secs)
	return msg
}

func (s _PointGimbalTypeSupport) Result() <no value>.MessageTypeSupport {
	return PointGimbal_ResultTypeSupport
}

func (s _PointGimbalTypeSupport) GetResult() <no value>.ServiceTypeSupport {
	return PointGimbal_GetResultTypeSupport
}

func (s _PointGimbalTypeSupport) NewGetResultResponse(status int8, result types.Message) <no value>.Message {
	msg := NewPointGimbal_GetResult_Response()
	msg.Status = status
	if result == nil {
		msg.Result = *NewPointGimbal_Result()
	} else {
		msg.Result = *result.(*PointGimbal_Result)
	}
	return msg
}

func (s _PointGimbalTypeSupport) CancelGoal() <no value>.ServiceTypeSupport {
	return action_msgs_srv.CancelGoalTypeSupport
}

func (s _PointGimbalTypeSupport) Feedback() <no value>.MessageTypeSupport {
	return PointGimbal_FeedbackTypeSupport
}

func (s _PointGimbalTypeSupport) FeedbackMessage() <no value>.MessageTypeSupport {
	return PointGimbal_FeedbackMessageTypeSupport
}

func (s _PointGimbalTypeSupport) NewFeedbackMessage(goalID *<no value>.GoalID, feedback <no value>.Message) <no value>.Message {
	msg := NewPointGimbal_FeedbackMessage()
	msg.GoalID.Uuid = *goalID
	msg.Feedback = *feedback.(*PointGimbal_Feedback)
	return msg
}

func (s _PointGimbalTypeSupport) GoalStatusArray() <no value>.MessageTypeSupport {
	return action_msgs_msg.GoalStatusArrayTypeSupport
}

func (s _PointGimbalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_action_type_support_handle__as2_msgs__action__PointGimbal())
}

// Modifying this variable is undefined behavior.
var PointGimbalTypeSupport <no value>.ActionTypeSupport = _PointGimbalTypeSupport{}

type PointGimbalFeedbackSender struct {
	sender <no value>.FeedbackSender
}

func (s *PointGimbalFeedbackSender) Send(msg *PointGimbal_Feedback) error {
	return s.sender.Send(msg)
}

type PointGimbalGoalHandle struct{
	*<no value>.GoalHandle

	Description *PointGimbal_Goal
}

func (g *PointGimbalGoalHandle) Accept() (*PointGimbalFeedbackSender, error) {
	s, err := g.GoalHandle.Accept()
	if err != nil {
		return nil, err
	}
	return &PointGimbalFeedbackSender{*s}, nil
}

type PointGimbalAction interface {
	ExecuteGoal(context.Context, *PointGimbalGoalHandle) (*PointGimbal_Result, error)
}

func NewPointGimbalAction(
	executeGoal func(context.Context, *PointGimbalGoalHandle) (*PointGimbal_Result, error),
) PointGimbalAction {
	return _PointGimbalFuncAction(executeGoal)
}

type _PointGimbalFuncAction func(context.Context, *PointGimbalGoalHandle) (*PointGimbal_Result, error)

func (a _PointGimbalFuncAction) ExecuteGoal(
	ctx context.Context, goal *PointGimbalGoalHandle,
) (*PointGimbal_Result, error) {
	return a(ctx, goal)
}

type _PointGimbalAction struct {
	action PointGimbalAction
}

func (a _PointGimbalAction) ExecuteGoal(ctx context.Context, handle *<no value>.GoalHandle) (<no value>.Message, error) {
	return a.action.ExecuteGoal(ctx, &PointGimbalGoalHandle{
		GoalHandle:  handle,
		Description: handle.Description.(*PointGimbal_Goal),
	})
}

func (a _PointGimbalAction) TypeSupport() <no value>.ActionTypeSupport {
	return PointGimbalTypeSupport
}

type PointGimbalServer struct{
	*<no value>.ActionServer
}

func NewPointGimbalServer(node *<no value>.Node, name string, action PointGimbalAction, opts *<no value>.ActionServerOptions) (*PointGimbalServer, error) {
	server, err := node.NewActionServer(name, _PointGimbalAction{action}, opts)
	if err != nil {
		return nil, err
	}
	return &PointGimbalServer{server}, nil
}

type PointGimbalFeedbackHandler func(context.Context, *PointGimbal_FeedbackMessage)

type PointGimbalStatusHandler func(context.Context, *action_msgs_msg.GoalStatus)

type PointGimbalClient struct{
	*<no value>.ActionClient
}

func NewPointGimbalClient(node *<no value>.Node, name string, opts *<no value>.ActionClientOptions) (*PointGimbalClient, error) {
	client, err := node.NewActionClient(name, PointGimbalTypeSupport, opts)
	if err != nil {
		return nil, err
	}
	return &PointGimbalClient{client}, nil
}

func (c *PointGimbalClient) WatchGoal(ctx context.Context, goal *PointGimbal_Goal, onFeedback PointGimbalFeedbackHandler) (*PointGimbal_GetResult_Response, *<no value>.GoalID, error) {
	var resp <no value>.Message
	var goalID *<no value>.GoalID
	var err error
	if onFeedback == nil {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, nil)
	} else {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, func(ctx context.Context, msg <no value>.Message) {
			onFeedback(ctx, msg.(*PointGimbal_FeedbackMessage))
		})
	}
	if r, ok := resp.(*PointGimbal_GetResult_Response); ok {
		return r, goalID, err
	}
	return nil, goalID, err
}

func (c *PointGimbalClient) SendGoal(ctx context.Context, goal *PointGimbal_Goal) (*PointGimbal_SendGoal_Response, *<no value>.GoalID, error) {
	resp, id, err := c.ActionClient.SendGoal(ctx, goal)
	if r, ok := resp.(*PointGimbal_SendGoal_Response); ok {
		return r, id, err
	}
	return nil, id, err
}

func (c *PointGimbalClient) SendGoalRequest(ctx context.Context, request *PointGimbal_SendGoal_Request) (*PointGimbal_SendGoal_Response, error) {
	resp, err := c.ActionClient.SendGoalRequest(ctx, request)
	if r, ok := resp.(*PointGimbal_SendGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *PointGimbalClient) GetResult(ctx context.Context, goalID *<no value>.GoalID) (*PointGimbal_GetResult_Response, error) {
	resp, err := c.ActionClient.GetResult(ctx, goalID)
	if r, ok := resp.(*PointGimbal_GetResult_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *PointGimbalClient) CancelGoal(ctx context.Context, request *action_msgs_srv.CancelGoal_Request) (*action_msgs_srv.CancelGoal_Response, error) {
	resp, err := c.ActionClient.CancelGoal(ctx, request)
	if r, ok := resp.(*action_msgs_srv.CancelGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *PointGimbalClient) WatchFeedback(ctx context.Context, goalID *<no value>.GoalID, handler PointGimbalFeedbackHandler) <-chan error {
	return c.ActionClient.WatchFeedback(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*PointGimbal_FeedbackMessage))
	})
}

func (c *PointGimbalClient) WatchStatus(ctx context.Context, goalID *<no value>.GoalID, handler PointGimbalStatusHandler) <-chan error {
	return c.ActionClient.WatchStatus(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*action_msgs_msg.GoalStatus))
	})
}
