// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/set_arming_state.h>
*/
import "C"

import (
	"context"
	"time"
	"unsafe"

	"github.com/okieraised/rclgo/humble"

	action_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/msg"
	action_msgs_srv "github.com/okieraised/monitoring-agent/internal/ros_msgs/action_msgs/srv"
)

func init() {
	<no value>.RegisterAction("as2_msgs/SetArmingState", SetArmingStateTypeSupport)
	<no value>.RegisterAction("as2_msgs/action/SetArmingState", SetArmingStateTypeSupport)
}

type _SetArmingStateTypeSupport struct {}

func (s _SetArmingStateTypeSupport) Goal() <no value>.MessageTypeSupport {
	return SetArmingState_GoalTypeSupport
}

func (s _SetArmingStateTypeSupport) SendGoal() <no value>.ServiceTypeSupport {
	return SetArmingState_SendGoalTypeSupport
}

func (s _SetArmingStateTypeSupport) NewSendGoalResponse(accepted bool, stamp time.Duration) <no value>.Message {
	msg := NewSetArmingState_SendGoal_Response()
	msg.Accepted = accepted
	secs := stamp.Truncate(time.Second)
	msg.Stamp.Sec = int32(secs)
	msg.Stamp.Nanosec = uint32(stamp - secs)
	return msg
}

func (s _SetArmingStateTypeSupport) Result() <no value>.MessageTypeSupport {
	return SetArmingState_ResultTypeSupport
}

func (s _SetArmingStateTypeSupport) GetResult() <no value>.ServiceTypeSupport {
	return SetArmingState_GetResultTypeSupport
}

func (s _SetArmingStateTypeSupport) NewGetResultResponse(status int8, result types.Message) <no value>.Message {
	msg := NewSetArmingState_GetResult_Response()
	msg.Status = status
	if result == nil {
		msg.Result = *NewSetArmingState_Result()
	} else {
		msg.Result = *result.(*SetArmingState_Result)
	}
	return msg
}

func (s _SetArmingStateTypeSupport) CancelGoal() <no value>.ServiceTypeSupport {
	return action_msgs_srv.CancelGoalTypeSupport
}

func (s _SetArmingStateTypeSupport) Feedback() <no value>.MessageTypeSupport {
	return SetArmingState_FeedbackTypeSupport
}

func (s _SetArmingStateTypeSupport) FeedbackMessage() <no value>.MessageTypeSupport {
	return SetArmingState_FeedbackMessageTypeSupport
}

func (s _SetArmingStateTypeSupport) NewFeedbackMessage(goalID *<no value>.GoalID, feedback <no value>.Message) <no value>.Message {
	msg := NewSetArmingState_FeedbackMessage()
	msg.GoalID.Uuid = *goalID
	msg.Feedback = *feedback.(*SetArmingState_Feedback)
	return msg
}

func (s _SetArmingStateTypeSupport) GoalStatusArray() <no value>.MessageTypeSupport {
	return action_msgs_msg.GoalStatusArrayTypeSupport
}

func (s _SetArmingStateTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_action_type_support_handle__as2_msgs__action__SetArmingState())
}

// Modifying this variable is undefined behavior.
var SetArmingStateTypeSupport <no value>.ActionTypeSupport = _SetArmingStateTypeSupport{}

type SetArmingStateFeedbackSender struct {
	sender <no value>.FeedbackSender
}

func (s *SetArmingStateFeedbackSender) Send(msg *SetArmingState_Feedback) error {
	return s.sender.Send(msg)
}

type SetArmingStateGoalHandle struct{
	*<no value>.GoalHandle

	Description *SetArmingState_Goal
}

func (g *SetArmingStateGoalHandle) Accept() (*SetArmingStateFeedbackSender, error) {
	s, err := g.GoalHandle.Accept()
	if err != nil {
		return nil, err
	}
	return &SetArmingStateFeedbackSender{*s}, nil
}

type SetArmingStateAction interface {
	ExecuteGoal(context.Context, *SetArmingStateGoalHandle) (*SetArmingState_Result, error)
}

func NewSetArmingStateAction(
	executeGoal func(context.Context, *SetArmingStateGoalHandle) (*SetArmingState_Result, error),
) SetArmingStateAction {
	return _SetArmingStateFuncAction(executeGoal)
}

type _SetArmingStateFuncAction func(context.Context, *SetArmingStateGoalHandle) (*SetArmingState_Result, error)

func (a _SetArmingStateFuncAction) ExecuteGoal(
	ctx context.Context, goal *SetArmingStateGoalHandle,
) (*SetArmingState_Result, error) {
	return a(ctx, goal)
}

type _SetArmingStateAction struct {
	action SetArmingStateAction
}

func (a _SetArmingStateAction) ExecuteGoal(ctx context.Context, handle *<no value>.GoalHandle) (<no value>.Message, error) {
	return a.action.ExecuteGoal(ctx, &SetArmingStateGoalHandle{
		GoalHandle:  handle,
		Description: handle.Description.(*SetArmingState_Goal),
	})
}

func (a _SetArmingStateAction) TypeSupport() <no value>.ActionTypeSupport {
	return SetArmingStateTypeSupport
}

type SetArmingStateServer struct{
	*<no value>.ActionServer
}

func NewSetArmingStateServer(node *<no value>.Node, name string, action SetArmingStateAction, opts *<no value>.ActionServerOptions) (*SetArmingStateServer, error) {
	server, err := node.NewActionServer(name, _SetArmingStateAction{action}, opts)
	if err != nil {
		return nil, err
	}
	return &SetArmingStateServer{server}, nil
}

type SetArmingStateFeedbackHandler func(context.Context, *SetArmingState_FeedbackMessage)

type SetArmingStateStatusHandler func(context.Context, *action_msgs_msg.GoalStatus)

type SetArmingStateClient struct{
	*<no value>.ActionClient
}

func NewSetArmingStateClient(node *<no value>.Node, name string, opts *<no value>.ActionClientOptions) (*SetArmingStateClient, error) {
	client, err := node.NewActionClient(name, SetArmingStateTypeSupport, opts)
	if err != nil {
		return nil, err
	}
	return &SetArmingStateClient{client}, nil
}

func (c *SetArmingStateClient) WatchGoal(ctx context.Context, goal *SetArmingState_Goal, onFeedback SetArmingStateFeedbackHandler) (*SetArmingState_GetResult_Response, *<no value>.GoalID, error) {
	var resp <no value>.Message
	var goalID *<no value>.GoalID
	var err error
	if onFeedback == nil {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, nil)
	} else {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, func(ctx context.Context, msg <no value>.Message) {
			onFeedback(ctx, msg.(*SetArmingState_FeedbackMessage))
		})
	}
	if r, ok := resp.(*SetArmingState_GetResult_Response); ok {
		return r, goalID, err
	}
	return nil, goalID, err
}

func (c *SetArmingStateClient) SendGoal(ctx context.Context, goal *SetArmingState_Goal) (*SetArmingState_SendGoal_Response, *<no value>.GoalID, error) {
	resp, id, err := c.ActionClient.SendGoal(ctx, goal)
	if r, ok := resp.(*SetArmingState_SendGoal_Response); ok {
		return r, id, err
	}
	return nil, id, err
}

func (c *SetArmingStateClient) SendGoalRequest(ctx context.Context, request *SetArmingState_SendGoal_Request) (*SetArmingState_SendGoal_Response, error) {
	resp, err := c.ActionClient.SendGoalRequest(ctx, request)
	if r, ok := resp.(*SetArmingState_SendGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *SetArmingStateClient) GetResult(ctx context.Context, goalID *<no value>.GoalID) (*SetArmingState_GetResult_Response, error) {
	resp, err := c.ActionClient.GetResult(ctx, goalID)
	if r, ok := resp.(*SetArmingState_GetResult_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *SetArmingStateClient) CancelGoal(ctx context.Context, request *action_msgs_srv.CancelGoal_Request) (*action_msgs_srv.CancelGoal_Response, error) {
	resp, err := c.ActionClient.CancelGoal(ctx, request)
	if r, ok := resp.(*action_msgs_srv.CancelGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *SetArmingStateClient) WatchFeedback(ctx context.Context, goalID *<no value>.GoalID, handler SetArmingStateFeedbackHandler) <-chan error {
	return c.ActionClient.WatchFeedback(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*SetArmingState_FeedbackMessage))
	})
}

func (c *SetArmingStateClient) WatchStatus(ctx context.Context, goalID *<no value>.GoalID, handler SetArmingStateStatusHandler) <-chan error {
	return c.ActionClient.WatchStatus(ctx, goalID, func(ctx context.Context, msg <no value>.Message) {
		handler(ctx, msg.(*action_msgs_msg.GoalStatus))
	})
}
