// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/set_offboard_mode.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/SetOffboardMode_GetResult", SetOffboardMode_GetResultTypeSupport)
	<no value>.RegisterService("as2_msgs/action/SetOffboardMode_GetResult", SetOffboardMode_GetResultTypeSupport)
}

type _SetOffboardMode_GetResultTypeSupport struct {}

func (s _SetOffboardMode_GetResultTypeSupport) Request() <no value>.MessageTypeSupport {
	return SetOffboardMode_GetResult_RequestTypeSupport
}

func (s _SetOffboardMode_GetResultTypeSupport) Response() <no value>.MessageTypeSupport {
	return SetOffboardMode_GetResult_ResponseTypeSupport
}

func (s _SetOffboardMode_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__SetOffboardMode_GetResult())
}

// Modifying this variable is undefined behavior.
var SetOffboardMode_GetResultTypeSupport <no value>.ServiceTypeSupport = _SetOffboardMode_GetResultTypeSupport{}

// SetOffboardMode_GetResultClient wraps <no value>.Client to provide type safe helper
// functions
type SetOffboardMode_GetResultClient struct {
	*<no value>.Client
}

// NewSetOffboardMode_GetResultClient creates and returns a new client for the
// SetOffboardMode_GetResult
func NewSetOffboardMode_GetResultClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*SetOffboardMode_GetResultClient, error) {
	client, err := node.NewClient(serviceName, SetOffboardMode_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetOffboardMode_GetResultClient{client}, nil
}

func (s *SetOffboardMode_GetResultClient) Send(ctx context.Context, req *SetOffboardMode_GetResult_Request) (*SetOffboardMode_GetResult_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetOffboardMode_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetOffboardMode_GetResultServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s SetOffboardMode_GetResultServiceResponseSender) SendResponse(resp *SetOffboardMode_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type SetOffboardMode_GetResultServiceRequestHandler func(*<no value>.ServiceInfo, *SetOffboardMode_GetResult_Request, SetOffboardMode_GetResultServiceResponseSender)

// SetOffboardMode_GetResultService wraps <no value>.Service to provide type safe helper
// functions
type SetOffboardMode_GetResultService struct {
	*<no value>.Service
}

// NewSetOffboardMode_GetResultService creates and returns a new service for the
// SetOffboardMode_GetResult
func NewSetOffboardMode_GetResultService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler SetOffboardMode_GetResultServiceRequestHandler) (*SetOffboardMode_GetResultService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*SetOffboardMode_GetResult_Request)
		responseSender := SetOffboardMode_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetOffboardMode_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetOffboardMode_GetResultService{service}, nil
}