// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/swarm_flocking.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/SwarmFlocking_GetResult", SwarmFlocking_GetResultTypeSupport)
	<no value>.RegisterService("as2_msgs/action/SwarmFlocking_GetResult", SwarmFlocking_GetResultTypeSupport)
}

type _SwarmFlocking_GetResultTypeSupport struct {}

func (s _SwarmFlocking_GetResultTypeSupport) Request() <no value>.MessageTypeSupport {
	return SwarmFlocking_GetResult_RequestTypeSupport
}

func (s _SwarmFlocking_GetResultTypeSupport) Response() <no value>.MessageTypeSupport {
	return SwarmFlocking_GetResult_ResponseTypeSupport
}

func (s _SwarmFlocking_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__SwarmFlocking_GetResult())
}

// Modifying this variable is undefined behavior.
var SwarmFlocking_GetResultTypeSupport <no value>.ServiceTypeSupport = _SwarmFlocking_GetResultTypeSupport{}

// SwarmFlocking_GetResultClient wraps <no value>.Client to provide type safe helper
// functions
type SwarmFlocking_GetResultClient struct {
	*<no value>.Client
}

// NewSwarmFlocking_GetResultClient creates and returns a new client for the
// SwarmFlocking_GetResult
func NewSwarmFlocking_GetResultClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*SwarmFlocking_GetResultClient, error) {
	client, err := node.NewClient(serviceName, SwarmFlocking_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SwarmFlocking_GetResultClient{client}, nil
}

func (s *SwarmFlocking_GetResultClient) Send(ctx context.Context, req *SwarmFlocking_GetResult_Request) (*SwarmFlocking_GetResult_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SwarmFlocking_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SwarmFlocking_GetResultServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s SwarmFlocking_GetResultServiceResponseSender) SendResponse(resp *SwarmFlocking_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type SwarmFlocking_GetResultServiceRequestHandler func(*<no value>.ServiceInfo, *SwarmFlocking_GetResult_Request, SwarmFlocking_GetResultServiceResponseSender)

// SwarmFlocking_GetResultService wraps <no value>.Service to provide type safe helper
// functions
type SwarmFlocking_GetResultService struct {
	*<no value>.Service
}

// NewSwarmFlocking_GetResultService creates and returns a new service for the
// SwarmFlocking_GetResult
func NewSwarmFlocking_GetResultService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler SwarmFlocking_GetResultServiceRequestHandler) (*SwarmFlocking_GetResultService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*SwarmFlocking_GetResult_Request)
		responseSender := SwarmFlocking_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SwarmFlocking_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SwarmFlocking_GetResultService{service}, nil
}