// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/swarm_flocking.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/SwarmFlocking_SendGoal", SwarmFlocking_SendGoalTypeSupport)
	<no value>.RegisterService("as2_msgs/action/SwarmFlocking_SendGoal", SwarmFlocking_SendGoalTypeSupport)
}

type _SwarmFlocking_SendGoalTypeSupport struct {}

func (s _SwarmFlocking_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return SwarmFlocking_SendGoal_RequestTypeSupport
}

func (s _SwarmFlocking_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return SwarmFlocking_SendGoal_ResponseTypeSupport
}

func (s _SwarmFlocking_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__SwarmFlocking_SendGoal())
}

// Modifying this variable is undefined behavior.
var SwarmFlocking_SendGoalTypeSupport <no value>.ServiceTypeSupport = _SwarmFlocking_SendGoalTypeSupport{}

// SwarmFlocking_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type SwarmFlocking_SendGoalClient struct {
	*<no value>.Client
}

// NewSwarmFlocking_SendGoalClient creates and returns a new client for the
// SwarmFlocking_SendGoal
func NewSwarmFlocking_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*SwarmFlocking_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, SwarmFlocking_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SwarmFlocking_SendGoalClient{client}, nil
}

func (s *SwarmFlocking_SendGoalClient) Send(ctx context.Context, req *SwarmFlocking_SendGoal_Request) (*SwarmFlocking_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SwarmFlocking_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SwarmFlocking_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s SwarmFlocking_SendGoalServiceResponseSender) SendResponse(resp *SwarmFlocking_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type SwarmFlocking_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *SwarmFlocking_SendGoal_Request, SwarmFlocking_SendGoalServiceResponseSender)

// SwarmFlocking_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type SwarmFlocking_SendGoalService struct {
	*<no value>.Service
}

// NewSwarmFlocking_SendGoalService creates and returns a new service for the
// SwarmFlocking_SendGoal
func NewSwarmFlocking_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler SwarmFlocking_SendGoalServiceRequestHandler) (*SwarmFlocking_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*SwarmFlocking_SendGoal_Request)
		responseSender := SwarmFlocking_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SwarmFlocking_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SwarmFlocking_SendGoalService{service}, nil
}