// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/takeoff.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("as2_msgs/Takeoff_SendGoal", Takeoff_SendGoalTypeSupport)
	<no value>.RegisterService("as2_msgs/action/Takeoff_SendGoal", Takeoff_SendGoalTypeSupport)
}

type _Takeoff_SendGoalTypeSupport struct {}

func (s _Takeoff_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return Takeoff_SendGoal_RequestTypeSupport
}

func (s _Takeoff_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return Takeoff_SendGoal_ResponseTypeSupport
}

func (s _Takeoff_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__Takeoff_SendGoal())
}

// Modifying this variable is undefined behavior.
var Takeoff_SendGoalTypeSupport <no value>.ServiceTypeSupport = _Takeoff_SendGoalTypeSupport{}

// Takeoff_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type Takeoff_SendGoalClient struct {
	*<no value>.Client
}

// NewTakeoff_SendGoalClient creates and returns a new client for the
// Takeoff_SendGoal
func NewTakeoff_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*Takeoff_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, Takeoff_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Takeoff_SendGoalClient{client}, nil
}

func (s *Takeoff_SendGoalClient) Send(ctx context.Context, req *Takeoff_SendGoal_Request) (*Takeoff_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Takeoff_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type Takeoff_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s Takeoff_SendGoalServiceResponseSender) SendResponse(resp *Takeoff_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type Takeoff_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *Takeoff_SendGoal_Request, Takeoff_SendGoalServiceResponseSender)

// Takeoff_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type Takeoff_SendGoalService struct {
	*<no value>.Service
}

// NewTakeoff_SendGoalService creates and returns a new service for the
// Takeoff_SendGoal
func NewTakeoff_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler Takeoff_SendGoalServiceRequestHandler) (*Takeoff_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*Takeoff_SendGoal_Request)
		responseSender := Takeoff_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, Takeoff_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &Takeoff_SendGoalService{service}, nil
}