// Code generated by ros2gen. DO NOT EDIT.

package sensor_msgs_srv

/*
#cgo LDFLAGS: "-L/opt/ros/jazzy/lib" "-Wl,-rpath=/opt/ros/jazzy/lib"

#cgo LDFLAGS: -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lsensor_msgs__rosidl_typesupport_c -lsensor_msgs__rosidl_generator_c
#cgo LDFLAGS: -lsensor_msgs__rosidl_typesupport_c -lsensor_msgs__rosidl_generator_c

#cgo CFLAGS: "-I/opt/ros/jazzy/include/action_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/example_interfaces"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/geometry_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/sensor_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/std_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/std_srvs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/test_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/sensor_msgs"

#cgo CFLAGS: "-I/opt/ros/jazzy/include/sensor_msgs"
*/
import "C"
