// Code generated by ros2gen. DO NOT EDIT.

package realsense2_camera_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <realsense2_camera_msgs/action/triggered_calibration.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("realsense2_camera_msgs/TriggeredCalibration_SendGoal", TriggeredCalibration_SendGoalTypeSupport)
	<no value>.RegisterService("realsense2_camera_msgs/action/TriggeredCalibration_SendGoal", TriggeredCalibration_SendGoalTypeSupport)
}

type _TriggeredCalibration_SendGoalTypeSupport struct {}

func (s _TriggeredCalibration_SendGoalTypeSupport) Request() <no value>.MessageTypeSupport {
	return TriggeredCalibration_SendGoal_RequestTypeSupport
}

func (s _TriggeredCalibration_SendGoalTypeSupport) Response() <no value>.MessageTypeSupport {
	return TriggeredCalibration_SendGoal_ResponseTypeSupport
}

func (s _TriggeredCalibration_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__realsense2_camera_msgs__action__TriggeredCalibration_SendGoal())
}

// Modifying this variable is undefined behavior.
var TriggeredCalibration_SendGoalTypeSupport <no value>.ServiceTypeSupport = _TriggeredCalibration_SendGoalTypeSupport{}

// TriggeredCalibration_SendGoalClient wraps <no value>.Client to provide type safe helper
// functions
type TriggeredCalibration_SendGoalClient struct {
	*<no value>.Client
}

// NewTriggeredCalibration_SendGoalClient creates and returns a new client for the
// TriggeredCalibration_SendGoal
func NewTriggeredCalibration_SendGoalClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*TriggeredCalibration_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, TriggeredCalibration_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &TriggeredCalibration_SendGoalClient{client}, nil
}

func (s *TriggeredCalibration_SendGoalClient) Send(ctx context.Context, req *TriggeredCalibration_SendGoal_Request) (*TriggeredCalibration_SendGoal_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*TriggeredCalibration_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type TriggeredCalibration_SendGoalServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s TriggeredCalibration_SendGoalServiceResponseSender) SendResponse(resp *TriggeredCalibration_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type TriggeredCalibration_SendGoalServiceRequestHandler func(*<no value>.ServiceInfo, *TriggeredCalibration_SendGoal_Request, TriggeredCalibration_SendGoalServiceResponseSender)

// TriggeredCalibration_SendGoalService wraps <no value>.Service to provide type safe helper
// functions
type TriggeredCalibration_SendGoalService struct {
	*<no value>.Service
}

// NewTriggeredCalibration_SendGoalService creates and returns a new service for the
// TriggeredCalibration_SendGoal
func NewTriggeredCalibration_SendGoalService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler TriggeredCalibration_SendGoalServiceRequestHandler) (*TriggeredCalibration_SendGoalService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*TriggeredCalibration_SendGoal_Request)
		responseSender := TriggeredCalibration_SendGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, TriggeredCalibration_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &TriggeredCalibration_SendGoalService{service}, nil
}