// Code generated by ros2gen. DO NOT EDIT.

package geographic_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <geographic_msgs/srv/get_geo_path.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	<no value>.RegisterService("geographic_msgs/GetGeoPath", GetGeoPathTypeSupport)
	<no value>.RegisterService("geographic_msgs/srv/GetGeoPath", GetGeoPathTypeSupport)
}

type _GetGeoPathTypeSupport struct {}

func (s _GetGeoPathTypeSupport) Request() <no value>.MessageTypeSupport {
	return GetGeoPath_RequestTypeSupport
}

func (s _GetGeoPathTypeSupport) Response() <no value>.MessageTypeSupport {
	return GetGeoPath_ResponseTypeSupport
}

func (s _GetGeoPathTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__geographic_msgs__srv__GetGeoPath())
}

// Modifying this variable is undefined behavior.
var GetGeoPathTypeSupport <no value>.ServiceTypeSupport = _GetGeoPathTypeSupport{}

// GetGeoPathClient wraps <no value>.Client to provide type safe helper
// functions
type GetGeoPathClient struct {
	*<no value>.Client
}

// NewGetGeoPathClient creates and returns a new client for the
// GetGeoPath
func NewGetGeoPathClient(node *<no value>.Node, serviceName string, options *<no value>.ClientOptions) (*GetGeoPathClient, error) {
	client, err := node.NewClient(serviceName, GetGeoPathTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetGeoPathClient{client}, nil
}

func (s *GetGeoPathClient) Send(ctx context.Context, req *GetGeoPath_Request) (*GetGeoPath_Response, *<no value>.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetGeoPath_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetGeoPathServiceResponseSender struct {
	sender <no value>.ServiceResponseSender
}

func (s GetGeoPathServiceResponseSender) SendResponse(resp *GetGeoPath_Response) error {
	return s.sender.SendResponse(resp)
}

type GetGeoPathServiceRequestHandler func(*<no value>.ServiceInfo, *GetGeoPath_Request, GetGeoPathServiceResponseSender)

// GetGeoPathService wraps <no value>.Service to provide type safe helper
// functions
type GetGeoPathService struct {
	*<no value>.Service
}

// NewGetGeoPathService creates and returns a new service for the
// GetGeoPath
func NewGetGeoPathService(node *<no value>.Node, name string, options *<no value>.ServiceOptions, handler GetGeoPathServiceRequestHandler) (*GetGeoPathService, error) {
	h := func(rmw *<no value>.ServiceInfo, msg <no value>.Message, rs <no value>.ServiceResponseSender) {
		m := msg.(*GetGeoPath_Request)
		responseSender := GetGeoPathServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetGeoPathTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetGeoPathService{service}, nil
}